build_docker_image:
  base_image: ubuntu:16.04

build_image:
  commands:
    $extend:
      - "apt-get update"
      - "curl -L https://github.com/alexdobin/STAR/archive/2.6.0c.tar.gz | tar xz"
      - "mv STAR-2.6.0c/bin/Linux_x86_64_static/* /usr/local/bin"
      - "rm -rf STAR-2.6.0c"
      - "git clone https://github.com/czbiohub/utilities.git"
      - "cd utilities"
      - "pip upgrade"
      - "pip install --upgrade -e ."
