functionality:
  name: demux
  namespace: ingestion
  description: |
    Convert `.bcl` files to `.fastq` files using bcl2fastq, bcl-convert or Cell Ranger mkfastq.
  info:
    name: Demux
    short_description: A generic pipeline for running bcl2fastq, bcl-convert or Cell Ranger mkfastq.
  authors:
    - __merge__: ../../../src/authors/toni_verbeiren.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../../src/authors/marijke_van_moerbeke.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/angela_pisco.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/samuel_d_souza.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author ]
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Input run directory
      example: bcl_dir
    - name: "--sample_sheet"
      alternatives: [ "-s" ]
      type: file
      required: true
      description: Pointer to the sample sheet
      example: bcl_dir
    - name: "--demultiplexer"
      type: string
      description: The multiplexer to use, one of bclconvert or mkfastq
      choices: [ bclconvert, bcl2fastq, mkfastq ]
      default: bcl2fastq
    - name: "--ignore_missing"
      type: boolean
      description: Should the demultiplexer ignore missing entities (filter, ...)
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
