functionality:
  name: "velocyto"
  namespace: "velocity"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Path to BAM file"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome"
    alternatives:
    - "-t"
    description: "Path to GTF file"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--barcode"
    alternatives:
    - "-b"
    description: "Valid barcodes file, to filter the bam. If --bcfile is not specified\
      \ all the cell barcodes will be included.\nCell barcodes should be specified\
      \ in the bcfile as the 'CB' tag for each read\n"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--without_umi"
    alternatives: []
    description: "foo"
    direction: "input"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Velocyto loom file"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--logic"
    alternatives:
    - "-l"
    description: "The logic to use for the filtering."
    example: []
    default:
    - "Default"
    required: false
    choices:
    - "Default"
    - "Permissive10X"
    - "Intermediate10X"
    - "ValidatedIntrons10X"
    - "Stricter10X"
    - "ObservedSpanning10X"
    - "Discordant10X"
    - "SmartSeq2"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Runs the velocity analysis on a BAM file, outputting a loom file."
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/cellranger_tiny_fastq"
  - type: "file"
    path: "../../../resources_test/rna_velocity"
  - type: "file"
    path: "../../../resources_test/reference_gencodev41_chr1"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.9"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages: []
    pip:
    - "numpy"
    - "Cython"
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  - type: "python"
    user: false
    packages: []
    pip:
    - "velocyto"
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  - type: "apt"
    packages:
    - "samtools"
    interactive: false
  test_setup: []
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/velocity/velocyto/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/velocity/velocyto"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/velocity/velocyto/velocyto"
  viash_version: "0.7.1"
  git_commit: "f2e21f1f2d74edac46fca1d608976ca77ca65d0f"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
