functionality:
  name: "cellranger_arc_aggr"
  namespace: "multiomics"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--data"
    description: "Path to the data"
    example:
    - "/path/to/data"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--reference_genome"
    description: "Path to the reference genome"
    example:
    - "/path/to/reference_genome"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Path to the output directory"
    example:
    - "/path/to/directory"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--run_id"
    description: "The run ID"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--peaks"
    description: "Path to the bed file to use for peak calling"
    example:
    - "/path/to/bed"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--neurips"
    description: "Unknown"
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Aggregate"
  usage: "cellranger_arc_aggr \\\n  --input /path/to/bcl \\\n  --sample_sheet sample_sheet.csv\
    \ \\\n  --output fastqs \\\n  --reports reports\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/cellranger_arc:2.0"
  target_organization: "czbiohub"
  target_registry: "docker.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/czbiohub/utilities"
  setup:
  - type: "python"
    user: false
    pip:
    - "numpy"
    - "pandas"
    - "scanpy"
    upgrade: true
- type: "native"
  id: "native"
info:
  config: "/home/runner/work/utilities/utilities/src/multiomics/cellranger_arc_aggr/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/utilities/utilities/target/native/multiomics/cellranger_arc_aggr"
  executable: "/home/runner/work/utilities/utilities/target/native/multiomics/cellranger_arc_aggr/cellranger_arc_aggr"
  viash_version: "0.7.3"
  git_commit: "54b6322faa244e2d61d6397b2f3dd02709fe25df"
  git_remote: "https://github.com/czbiohub/utilities"
