functionality:
  name: "cellranger_arc_aggr"
  namespace: "multiomics"
  version: "main_build"
  authors: []
  arguments:
  - type: "file"
    name: "--data"
    alternatives: []
    description: "Path to the data"
    example:
    - "/path/to/data"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--reference_genome"
    alternatives: []
    description: "Path to the reference genome"
    example:
    - "/path/to/reference_genome"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "Path to the output directory"
    example:
    - "/path/to/directory"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--run_id"
    alternatives: []
    description: "The run ID"
    example: []
    default: []
    required: true
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--peaks"
    alternatives: []
    description: "Path to the bed file to use for peak calling"
    example:
    - "/path/to/bed"
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--neurips"
    alternatives: []
    description: "Unknown"
    example: []
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Aggregate"
  usage: "cellranger_arc_aggr \\\n  --input /path/to/bcl \\\n  --sample_sheet sample_sheet.csv\
    \ \\\n  --output fastqs \\\n  --reports reports\n"
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/cellranger_arc:2.0"
  target_organization: "czbiohub"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/czbiohub/utilities"
  setup:
  - type: "python"
    user: false
    packages: []
    pip:
    - "numpy"
    - "pandas"
    - "scanpy"
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
- type: "native"
  id: "native"
info:
  config: "/home/runner/work/utilities/utilities/src/multiomics/cellranger_arc_aggr/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/utilities/utilities/target/native/multiomics/cellranger_arc_aggr"
  executable: "/home/runner/work/utilities/utilities/target/native/multiomics/cellranger_arc_aggr/cellranger_arc_aggr"
  viash_version: "0.7.0"
  git_commit: "ad0386df03d60cece1c72054e63a16ff43f6edff"
  git_remote: "https://github.com/czbiohub/utilities"
