functionality:
  name: "bd_rhapsody"
  namespace: "mapping"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments: []
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "string"
      name: "--mode"
      alternatives: []
      description: "Whether to run a whole transcriptome analysis (WTA) or a targeted\
        \ analysis."
      example:
      - "wta"
      default: []
      required: true
      choices:
      - "wta"
      - "targeted"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      alternatives:
      - "-i"
      description: "Path to your read files in the FASTQ.GZ format. You may specify\
        \ as many R1/R2 read pairs as you want."
      example:
      - "input.fastq.gz"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--reference"
      alternatives:
      - "-r"
      - "--reference_genome"
      description: "Refence to map to. For `--mode wta`, this is the path to STAR\
        \ index as a tar.gz file. For `--mode targeted`, this is the path to mRNA\
        \ reference file for pre-designed, supplemental, or custom panel, in FASTA\
        \ format"
      example:
      - "reference_genome.tar.gz|reference.fasta"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--transcriptome_annotation"
      alternatives:
      - "-t"
      description: "Path to GTF annotation file (only for `--mode wta`)."
      example:
      - "transcriptome.gtf"
      default: []
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--abseq_reference"
      alternatives:
      - "-a"
      description: "Path to the AbSeq reference file in FASTA format. Only needed\
        \ if BD AbSeq Ab-Oligos are used."
      example:
      - "abseq_reference.fasta"
      default: []
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--supplemental_reference"
      alternatives:
      - "-s"
      description: "Path to the supplemental reference file in FASTA format. Only\
        \ needed if there are additional transgene sequences used in the experiment\
        \ (only for `--mode wta`)."
      example:
      - "supplemental_reference.fasta"
      default: []
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--sample_prefix"
      alternatives: []
      description: "Specify a run name to use as the output file base name. Use only\
        \ letters, numbers, or hyphens. Do not use special characters or spaces."
      example: []
      default:
      - "sample"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Output folder. Output still needs to be processed further."
      example:
      - "output_dir"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Putative cell calling settings"
    arguments:
    - type: "string"
      name: "--putative_cell_call"
      alternatives: []
      description: "Specify the dataset to be used for putative cell calling. For\
        \ putative cell calling using an AbSeq dataset, please provide an AbSeq_Reference\
        \ fasta file above."
      example:
      - "mRNA"
      default: []
      required: false
      choices:
      - "mRNA"
      - "AbSeq_Experimental"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--exact_cell_count"
      alternatives: []
      description: "Exact cell count - Set a specific number (>=1) of cells as putative,\
        \ based on those with the highest error-corrected read count"
      example:
      - 10000
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--disable_putative_calling"
      alternatives: []
      description: "Disable Refined Putative Cell Calling - Determine putative cells\
        \ using only the basic algorithm (minimum second derivative along the cumulative\
        \ reads curve). The refined algorithm attempts to remove false positives and\
        \ recover false negatives, but may not be ideal for certain complex mixtures\
        \ of cell types. Does not apply if Exact Cell Count is set."
      direction: "input"
      dest: "par"
  - name: "Subsample arguments"
    arguments:
    - type: "double"
      name: "--subsample"
      alternatives: []
      description: "A number >1 or fraction (0 < n < 1) to indicate the number or\
        \ percentage of reads to subsample."
      example:
      - 0.01
      default: []
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--subsample_seed"
      alternatives: []
      description: "A seed for replicating a previous subsampled run."
      example:
      - 3445
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Multiplex arguments"
    arguments:
    - type: "string"
      name: "--sample_tags_version"
      alternatives: []
      description: "Specify if multiplexed run."
      example:
      - "human"
      default: []
      required: false
      choices:
      - "human"
      - "hs"
      - "mouse"
      - "mm"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--tag_names"
      alternatives: []
      description: "Tag_Names (optional) - Specify the tag number followed by '-'\
        \ and the desired sample name to appear in Sample_Tag_Metrics.csv.\nDo not\
        \ use the special characters: &, (), [], {},  <>, ?, |\n"
      example:
      - "4-mySample"
      - "9-myOtherSample"
      - "6-alsoThisSample"
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
  - name: "VDJ arguments"
    arguments:
    - type: "string"
      name: "--vdj_version"
      alternatives: []
      description: "Specify if VDJ run."
      example:
      - "human"
      default: []
      required: false
      choices:
      - "human"
      - "mouse"
      - "humanBCR"
      - "humanBCR"
      - "humanTCR"
      - "mouseBCR"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "CWL-runner arguments"
    arguments:
    - type: "boolean"
      name: "--parallel"
      alternatives: []
      description: "Run jobs in parallel."
      example: []
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--timestamps"
      alternatives: []
      description: "Add timestamps to the errors, warnings, and notifications."
      direction: "input"
      dest: "par"
    - type: "boolean_true"
      name: "--dryrun"
      alternatives: []
      description: "If true, the output directory will only contain the CWL input\
        \ files, but the pipeline itself will not be executed."
      direction: "input"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "rhapsody_wta_1.10.1_nodocker.cwl"
  - type: "file"
    path: "rhapsody_targeted_1.10.1_nodocker.cwl"
  description: "A wrapper for the BD Rhapsody Analysis CWL v1.10.1 pipeline.\n\nThe\
    \ CWL pipeline file is obtained by cloning 'https://bitbucket.org/CRSwDev/cwl/src/master/'\
    \ and removing all objects with class 'DockerRequirement' from the YML.\n\nThis\
    \ pipeline can be used for a targeted analysis (with `--mode targeted`) or for\
    \ a whole transcriptome analysis (with `--mode wta`).\n\n* If mode is `\"targeted\"\
    `, then either the `--reference` or `--abseq_reference` parameters must be defined.\n\
    * If mode is `\"wta\"`, then `--reference` and `--transcriptome_annotation` must\
    \ be defined, `--abseq_reference` and `--supplemental_reference` is optional.\n\
    \nThe reference_genome and transcriptome_annotation files can be generated with\
    \ the make_reference pipeline.\nAlternatively, BD also provides standard references\
    \ which can be downloaded from these locations:\n\n  - Human: http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-WTA/GRCh38-PhiX-gencodev29/\n\
    \  - Mouse: http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-WTA/GRCm38-PhiX-gencodevM19/\n"
  test_resources:
  - type: "bash_script"
    path: "run_memory_test.sh"
    is_executable: true
  - type: "bash_script"
    path: "run_wta_test.sh"
    is_executable: true
  - type: "bash_script"
    path: "run_targeted_test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/bdrhap_vdj"
  - type: "file"
    path: "../../../resources_test/bdrhap_5kjrt"
  - type: "file"
    path: "../../../resources_test/reference_gencodev41_chr1/"
  info:
    name: "BD Rhapsody"
    short_description: "A wrapper for the BD Rhapsody Analysis CWL v1.10.1 pipeline"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/bd_rhapsody:1.10.1"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "pandas"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    - "highcpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/mapping/bd_rhapsody/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/mapping/bd_rhapsody"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/mapping/bd_rhapsody/bd_rhapsody"
  viash_version: "0.7.1"
  git_commit: "f2e21f1f2d74edac46fca1d608976ca77ca65d0f"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
