functionality:
  name: "concat"
  namespace: "dataflow"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Paths to the different samples to be concatenated."
    example:
    - "sample_paths"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ","
    dest: "par"
  - type: "string"
    name: "--input_id"
    alternatives: []
    description: "Names of the different samples that have to be concatenated.  Must\
      \ be specified when using '--mode move'.\nIn this case, the ids will be used\
      \ for the columns names of the dataframes registring the conflicts.\nIf specified,\
      \ must be of same length as `--input`.\n"
    example: []
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: true
    multiple_sep: ","
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    example:
    - "output.h5mu"
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--output_compression"
    alternatives: []
    description: "The compression format to be used on the output h5mu object."
    example:
    - "gzip"
    default: []
    required: false
    choices:
    - "gzip"
    - "lzf"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obs_sample_name"
    alternatives: []
    description: "Name of the .obs key under which to add the sample names."
    example: []
    default:
    - "sample_id"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--other_axis_mode"
    alternatives: []
    description: "How to handle the merging of other axis (var, obs, ...).\n\n - None:\
      \ keep no data\n - same: only keep elements of the matrices which are the same\
      \ in each of the samples\n - unique: only keep elements for which there is only\
      \ 1 possible value (1 value that can occur in multiple samples)\n - first: keep\
      \ the annotation from the first sample\n - only: keep elements that show up\
      \ in only one of the objects (1 unique element in only 1 sample)\n - move: identical\
      \ to 'same', but moving the conflicting values to .varm or .obsm\n"
    example: []
    default:
    - "move"
    required: false
    choices:
    - "same"
    - "unique"
    - "first"
    - "only"
    - "concat"
    - "move"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Concatenates several uni-modal samples in .h5mu files into a single\
    \ file.\n"
  test_resources:
  - type: "python_script"
    path: "test_concat.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/concat_test_data/e18_mouse_brain_fresh_5k_filtered_feature_bc_matrix_subset_unique_obs.h5mu"
  - type: "file"
    path: "../../../resources_test/concat_test_data/human_brain_3k_filtered_feature_bc_matrix_subset_unique_obs.h5mu"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "mudata~=0.2.0"
    - "anndata~=0.8.0"
    - "pandas~=2.0.0"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup:
  - type: "python"
    user: false
    packages:
    - "viashpy"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "midcpu"
    - "highmem"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/dataflow/concat/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/dataflow/concat"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/dataflow/concat/concat"
  viash_version: "0.7.1"
  git_commit: "275ed3f9481a5183da75c603edd18436aee5daa4"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
