functionality:
  name: "process_10x"
  namespace: "mapping"
  version: "main_build"
  authors:
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments: []
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "string"
      name: "--id"
      alternatives: []
      description: "ID of the sample."
      example:
      - "foo"
      default: []
      required: true
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      alternatives: []
      description: "The fastq.gz files to align. Can also be a single directory containing\
        \ fastq.gz files."
      example:
      - "sample_S1_L001_R1_001.fastq.gz"
      - "sample_S1_L001_R2_001.fastq.gz"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--reference"
      alternatives: []
      description: "The path to Cell Ranger reference tar.gz file."
      example:
      - "reference.tar.gz"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--output_raw"
      alternatives: []
      description: "The cellranger output directory."
      example: []
      default:
      - "$id.output_raw"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--output_h5mu"
      alternatives: []
      description: "The output h5mu."
      example: []
      default:
      - "$id.output_h5mu.h5mu"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/utilities/utilities/src/mapping/process_10x/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/utilities/utilities/target/nextflow/mapping/process_10x"
  executable: "/home/runner/work/utilities/utilities/target/nextflow/mapping/process_10x/process_10x"
  viash_version: "0.7.0"
  git_commit: "ad0386df03d60cece1c72054e63a16ff43f6edff"
  git_remote: "https://github.com/czbiohub/utilities"
