functionality:
  name: "from_cellranger_multi_to_h5mu"
  namespace: "convert"
  version: "dev"
  description: |
    Converts the output from cellranger multi to a single .h5mu file.
    By default, will map the following library type names to modality names:
      - Gene Expression: rna
      - Peaks: atac
      - Antibody Capture: prot
      - VDJ: vdj
      - VDJ-T: vdj_t
      - VDJ-B: vdj_b
      - CRISPR Guide Capture: crispr
      - Multiplexing Capture: hashing
    
    Other library types have their whitepace removed and dashes replaced by
    underscores to generate the modality name.

    Currently does not allow parsing the output from cell barcode demultiplexing.
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input folder. Must contain the output from a cellranger multi run.
      example: input_dir_containing_modalities
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      example: output.h5mu
      direction: output
    - name: "--output_compression"
      type: string
      choices: ["gzip", "lzf"]
      required: false
      example: "gzip"
    - name: "--uns_metrics"
      type: string
      description: Name of the .uns slot under which to QC metrics (if any).
      default: "metrics_cellranger"
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/10x_5k_anticmv
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: python
        packages:
          - scanpy~=1.9.2
          - mudata~=0.2.0
          - anndata~=0.8.0
          - scirpy~=0.11.1
          - pandas~=2.0.0
  - type: nextflow
    variant: vdsl3

