functionality:
  name: "bbknn"
  namespace: "neighbors"
  version: "main_build"
  authors:
  - name: "Dries De Maeyer"
    email: "ddemaeyer@gmail.com"
    roles:
    - "author"
    props:
      github: "ddemaeyer"
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input h5mu file"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--modality"
    alternatives: []
    example: []
    default:
    - "rna"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obsm_input"
    alternatives: []
    description: "The dimensionality reduction in `.obsm` to use for neighbour detection.\
      \ Defaults to X_pca."
    example: []
    default:
    - "X_pca"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obs_batch"
    alternatives: []
    description: ".obs column name discriminating between your batches."
    example: []
    default:
    - "batch"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output .h5mu file."
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--output_compression"
    alternatives: []
    description: "The compression format to be used on the output h5mu object."
    example:
    - "gzip"
    default: []
    required: false
    choices:
    - "gzip"
    - "lzf"
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--uns_output"
    alternatives: []
    description: "Mandatory .uns slot to store various neighbor output objects."
    example: []
    default:
    - "neighbors"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obsp_distances"
    alternatives: []
    description: "In which .obsp slot to store the distance matrix between the resulting\
      \ neighbors."
    example: []
    default:
    - "distances"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obsp_connectivities"
    alternatives: []
    description: "In which .obsp slot to store the connectivities matrix between the\
      \ resulting neighbors."
    example: []
    default:
    - "connectivities"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_neighbors_within_batch"
    alternatives: []
    description: "How many top neighbours to report for each batch; total number of\
      \ neighbours in the initial k-nearest-neighbours computation will be this number\
      \ times the number of batches."
    example: []
    default:
    - 3
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_pcs"
    alternatives: []
    description: "How many dimensions (in case of PCA, principal components) to use\
      \ in the analysis."
    example: []
    default:
    - 50
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_trim"
    alternatives: []
    description: "Trim the neighbours of each cell to these many top connectivities.\
      \ May help with population independence and improve the tidiness of clustering.\
      \ The lower the value the more independent the individual populations, at the\
      \ cost of more conserved batch effect. If `None` (default), sets the parameter\
      \ value automatically to 10 times `neighbors_within_batch` times the number\
      \ of batches. Set to 0 to skip."
    example: []
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "BBKNN network generation\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.8"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "mudata~=0.2.0"
    - "anndata~=0.8.0"
    - "scanpy~=1.9.2"
    - "bbknn"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/neighbors/bbknn/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/neighbors/bbknn"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/neighbors/bbknn/bbknn"
  viash_version: "0.7.1"
  git_commit: "275ed3f9481a5183da75c603edd18436aee5daa4"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
