functionality:
  name: "run_cellxgene"
  namespace: "interactive"
  version: "main_build"
  authors: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Directory to mount"
    example: []
    default:
    - "."
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--port"
    alternatives:
    - "-p"
    description: "Port to use"
    example: []
    default:
    - "5005"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: ""
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:focal"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args:
  - "$( echo $VIASH_PAR_PORT | sed 's/..*/-p &:&/' )"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    label: []
    add: []
    copy: []
    run:
    - "apt update && apt upgrade -y"
    build_args: []
    env: []
  - type: "apt"
    packages:
    - "build-essential libxml2-dev python3-dev python3-pip zlib1g-dev python3-requests\
      \ python3-aiohttp python-is-python3"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "cellxgene"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/interactive/run_cellxgene/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/interactive/run_cellxgene"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/interactive/run_cellxgene/run_cellxgene"
  viash_version: "0.7.1"
  git_commit: "87117a5a2cbcae3a1822c26b043045a286f5e687"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
