functionality:
  name: "prot_singlesample"
  namespace: "multiomics"
  description: "Processing unimodal single-sample CITE-seq data."
  authors:
    - __merge__: ../../../src/authors/dries_de_maeyer.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author ]
  argument_groups:
    - name: "Input"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          type: file
          required: true
          description: Path to the sample.
          example: dataset.h5mu
    - name: "Output"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
    - name: "Filtering options"
      arguments:
        - name: "--min_counts"
          example: 200
          type: integer
          description: Minimum number of counts captured per cell.
        - name: "--max_counts"
          example: 5000000
          type: integer
          description: Maximum number of counts captured per cell.
  
        - name: "--min_proteins_per_cell"
          type: integer
          example: 200
          description: Minimum of non-zero values per cell.
        - name: "--max_proteins_per_cell"
          example: 1500000
          type: integer
          description: Maximum of non-zero values per cell.

        - name: "--min_cells_per_protein"
          example: 3
          type: integer
          description: Minimum of non-zero values per gene.

        - name: "--min_fraction_mito"
          example: 0
          type: double
          description: Minimum fraction of proteins that are mitochondrial.
        - name: "--max_fraction_mito"
          type: double
          example: 0.2
          description: Maximum fraction of proteins that are mitochondrial.
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf