functionality:
  name: scale
  namespace: "transform"
  version: "dev"
  description: |
    Scale data to unit variance and zero mean.
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
  arguments:
    # input
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file.
      direction: input
      required: true
      example: input.h5mu
    - name: "--modality"
      description: List of modalities to process.
      type: string
      default: "rna"
      required: false
    - name: "--max_value"
      required: false
      type: double
      description: Clip (truncate) to this value after scaling. Does not clip by default.
    - name: "--zero_center"
      type: boolean
      default: true
      required: false
      description: If False, omit zero-centering variables, which allows to handle sparse input efficiently.
    # output
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      direction: output
      required: true
      default: output.h5mu
    - name: "--output_compression"
      type: string
      description: The compression format to be used on the output h5mu object.
      choices: ["gzip", "lzf"]
      required: false
      example: "gzip"
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.10-slim-bullseye
    setup:
      - type: docker
        run: apt update && apt upgrade -y
      - type: apt
        packages: libhdf5-dev
      - type: python
        packages:
          - scanpy~=1.9.2
          - mudata~=0.2.0
          - anndata~=0.8.0
  - type: nextflow
  - type: native