functionality:
  name: "harmonypy"
  namespace: "integrate"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "contributor"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input h5mu file"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output h5mu file."
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--modality"
    alternatives: []
    example: []
    default:
    - "rna"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obsm_input"
    alternatives: []
    description: "Which .obsm slot to use as a starting PCA embedding."
    example: []
    default:
    - "X_pca"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obsm_output"
    alternatives: []
    description: "In which .obsm slot to store the resulting integrated embedding."
    example: []
    default:
    - "X_pca_integrated"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "double"
    name: "--theta"
    alternatives: []
    description: "Diversity clustering penalty parameter. Specify for each variable\
      \ in group.by.vars. theta=0 does not encourage any diversity. Larger values\
      \ of theta result in more diverse clusters."
    example: []
    default:
    - 2.0
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--obs_covariates"
    alternatives: []
    description: "The .obs field(s) that define the covariate(s) to regress out."
    example:
    - "batch"
    - "sample"
    default: []
    required: true
    choices: []
    direction: "input"
    multiple: true
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Performs Harmony integration based as described in https://github.com/immunogenomics/harmony.\
    \ Based on an implementation in python from https://github.com/slowkow/harmonypy"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "mudata~=0.2.0"
    - "anndata~=0.8.0"
    - "harmonypy~=0.0.6"
    - "scanpy~=1.9.2"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    - "highcpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/integrate/harmonypy/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/integrate/harmonypy"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/integrate/harmonypy/harmonypy"
  viash_version: "0.7.0"
  git_commit: "79131063f70d256bcdd4e47f0572f968cc71938b"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
