functionality:
  name: add_id
  namespace: "metadata"
  version: "dev"
  description: |
    Add id of .obs. Also allows to make .obs_names (the .obs index) unique 
    by prefixing the values with an unique id per .h5mu file.
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Path to the input .h5mu.
      required: true
      example: sample_path
    - name: "--input_id"
      type: string
      description: "The input id."
      required: true
    - name: "--obs_output"
      type: string
      required: false
      description: "Name of the .obs column where to store the id."
      default: "sample_id"
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      example: "output.h5mu"
    - name: "--output_compression"
      type: string
      description: The compression format to be used on the output h5mu object.
      choices: ["gzip", "lzf"]
      required: false
      example: "gzip"
    - name: "--make_observation_keys_unique"
      type: boolean_true
      description: Join the id to the .obs index (.obs_names).
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/concat_test_data/e18_mouse_brain_fresh_5k_filtered_feature_bc_matrix_subset_unique_obs.h5mu
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
  - type: native
  - type: nextflow