functionality:
  name: "filter_10xh5"
  namespace: "process_10xh5"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments:
  - type: "file"
    name: "--input"
    alternatives: []
    description: "An h5 file from the 10x genomics website."
    example:
    - "pbmc_1k_protein_v3_raw_feature_bc_matrix.h5"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "Output h5 file."
    example:
    - "pbmc_1k_protein_v3_raw_feature_bc_matrix_filtered.h5"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--min_library_size"
    alternatives: []
    description: "Minimum library size."
    example: []
    default:
    - 0
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--min_cells_per_gene"
    alternatives: []
    description: "Minimum number of cells per gene."
    example: []
    default:
    - 0
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--keep_feature_types"
    alternatives: []
    description: "Specify which feature types will never be filtered out"
    example:
    - "Antibody Capture"
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: true
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--verbose"
    alternatives: []
    description: "Increase verbosity"
    direction: "input"
    dest: "par"
  argument_groups: []
  resources:
  - type: "r_script"
    path: "script.R"
    is_executable: true
  description: "Filter a 10x h5 dataset.\n"
  usage: "filter_10xh5 \\\n  --input pbmc_1k_protein_v3_raw_feature_bc_matrix.h5 \\\
    \n  --output pbmc_1k_protein_v3_raw_feature_bc_matrix_filtered.h5 \\\n  --min_library_size\
    \ 1000 --min_cells_per_gene 300\n"
  test_resources:
  - type: "r_script"
    path: "run_test.R"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "eddelbuettel/r2u:22.04"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "libhdf5-dev python3-pip python3-dev"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "scanpy~=1.9.2"
    - "anndata~=0.8.0"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  - type: "r"
    packages: []
    cran:
    - "testthat"
    - "anndata"
    - "hdf5r"
    bioc: []
    git: []
    github: []
    gitlab: []
    bitbucket: []
    svn: []
    url: []
    script: []
    bioc_force_install: false
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/process_10xh5/filter_10xh5/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/process_10xh5/filter_10xh5"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/process_10xh5/filter_10xh5/filter_10xh5"
  viash_version: "0.7.1"
  git_commit: "87117a5a2cbcae3a1822c26b043045a286f5e687"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
