functionality:
  name: from_h5ad_to_h5mu
  namespace: "convert"
  version: "dev"
  description: |
    Converts a single layer h5ad file into a single MuData object
  authors:
    - __merge__: ../../authors/dries_de_maeyer.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5ad files
      default: input.h5ad
      direction: input
      required: true
      multiple: true
    - name: "--modality"
      type: string
      default: "rna"
      required: false
      multiple: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output MuData file.
      default: output.h5mu
      direction: output
    - name: "--output_compression"
      type: string
      choices: ["gzip", "lzf"]
      required: false
      example: "gzip"
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
  - type: nextflow
