functionality:
  name: "full_pipeline"
  namespace: "multiomics"
  description: "A pipeline to analyse multiple multiomics samples."
  authors:
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          required: true
          example: input.h5mu
          type: file
        - name: "--obs_covariates"
          type: string
          description: "The .obs field(s) that define the covariate(s) to regress out."
          example: ["batch", "sample"]
          default: ["sample_id"]
          multiple: true
          required: false
    - name: "RNA filtering options"
      arguments:
        - name: "--rna_min_counts"
          example: 200
          type: integer
          description: Minimum number of counts captured per cell.
        - name: "--rna_max_counts"
          example: 5000000
          type: integer
          description: Maximum number of counts captured per cell.
  
        - name: "--rna_min_vars_per_cell"
          type: integer
          example: 200
          description: Minimum of non-zero values per cell.
        - name: "--rna_max_vars_per_cell"
          example: 1500000
          type: integer
          description: Maximum of non-zero values per cell.

        - name: "--min_cells_per_protein"
          example: 3
          type: integer
          description: Minimum of non-zero values per antibody.

        - name: "--rna_min_fraction_mito"
          example: 0
          type: double
          description: Minimum fraction of UMIs that are mitochondrial.
        - name: "--rna_max_fraction_mito"
          type: double
          example: 0.2
          description: Maximum fraction of UMIs that are mitochondrial.
    - name: "CITE-seq filtering options"
      arguments:
        - name: "--prot_min_counts"
          description: Minimum number of counts per cell.
          type: integer
          example: 3
        - name: "--prot_max_counts"
          description: Minimum number of counts per cell.
          type: integer
          example: 5000000

        - name: "--prot_min_vars_per_cell"
          type: integer
          example: 200
          description: Minimum of non-zero values per cell.
        - name: "--prot_max_vars_per_cell"
          description: Maximum of non-zero values per cell.
          type: integer
          example: 100000000

        - name: "--prot_min_cells_per_protein"
          example: 3
          type: integer
          description: Minimum of non-zero values per protein.
        
        - name: "--prot_min_fraction_mito"
          example: 0
          type: double
          description: Minimum fraction of proteins that are mitochondrial.
        - name: "--prot_max_fraction_mito"
          example: 0.2
          type: double
          description: Maximum fraction of proteins that are mitochondrial.
    - name: "Highly variable gene detection"
      arguments:
        - name: "--filter_with_hvg_var_output"
          required: false
          type: string
          default: "filter_with_hvg"
          description: In which .var slot to store a boolean array corresponding to the highly variable genes.
        - name: "--filter_with_hvg_obs_batch_key"
          type: string
          default: "sample_id"
          required: false
          description: |
            If specified, highly-variable genes are selected within each batch separately and merged. This simple 
            process avoids the selection of batch-specific genes and acts as a lightweight batch correction method.
    - name: "QC metrics calculation options"
      arguments:
        - name: "--var_qc_metrics"
          description: |
            Keys to select a boolean (containing only True or False) column from .var.
            For each cell, calculate the proportion of total values for genes which are labeled 'True', 
            compared to the total sum of the values for all genes.
          type: string
          multiple: True
          multiple_sep: ','
          required: false
          default: ["filter_with_hvg"]
          example: "ercc,highly_variable"
        - name: "--top_n_vars"
          type: integer
          description: |
            Number of top vars to be used to calculate cumulative proportions.
            If not specified, proportions are not calculated. `--top_n_vars 20,50` finds
            cumulative proportion to the 20th and 50th most expressed vars.
          multiple: true
          multiple_sep: ','
          required: false
          default: [50, 100, 200, 500]
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
