functionality:
  name: "star_build_reference"
  namespace: "mapping"
  version: "main_build"
  authors:
  - name: "Dries Schaumont"
    email: "dries@data-intuitive.com"
    roles:
    - "author"
    props:
      github: "DriesSchaumont"
      orcid: "0000-0002-4389-0440"
  arguments: []
  argument_groups:
  - name: "Input/Output"
    arguments:
    - type: "file"
      name: "--genome_fasta"
      alternatives:
      - "--genomeFastaFiles"
      description: "The fasta files to be included in the reference. Corresponds to\
        \ the --genomeFastaFiles argument in the STAR command."
      example:
      - "chr1.fasta"
      - "chr2.fasta"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: true
      multiple_sep: " "
      dest: "par"
    - type: "file"
      name: "--transcriptome_gtf"
      alternatives:
      - "--sjdbGTFfile"
      description: "Specifies the path to the file with annotated transcripts in the\
        \ standard GTF\nformat. STAR will extract splice junctions from this file\
        \ and use them to greatly improve\naccuracy of the mapping. Corresponds to\
        \ the --sjdbGTFfile argument in the STAR command.\n"
      example: []
      default: []
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--output"
      alternatives:
      - "--genomeDir"
      description: "Path to output directory. Corresponds to the --genomeDir argument\
        \ in the STAR command."
      example:
      - "/path/to/foo"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Genome indexing arguments"
    arguments:
    - type: "integer"
      name: "--genomeSAindexNbases"
      alternatives: []
      description: "Length (bases) of the SA pre-indexing string. Typically between\
        \ 10 and 15.\nLonger strings will use much more memory, but allow faster searches.\
        \ For small\ngenomes, the parameter {genomeSAindexNbases must be scaled down\
        \ to\nmin(14, log2(GenomeLength)/2 - 1).\n"
      example: []
      default:
      - 14
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Create a reference for STAR from a set of fasta files."
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/cellranger_tiny_fastq"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    label: []
    add: []
    copy: []
    run: []
    build_args: []
    env:
    - "STAR_VERSION 2.7.10a"
    - "PACKAGES gcc g++ make wget zlib1g-dev unzip"
  - type: "docker"
    label: []
    add: []
    copy: []
    run:
    - "apt-get update && \\\n  apt-get install -y --no-install-recommends ${PACKAGES}\
      \ && \\\n  cd /tmp && \\\n  wget --no-check-certificate https://github.com/alexdobin/STAR/archive/refs/tags/${STAR_VERSION}.zip\
      \ && \\\n  unzip ${STAR_VERSION}.zip && \\\n  cd STAR-${STAR_VERSION}/source\
      \ && \\\n  make STARstatic CXXFLAGS_SIMD=-std=c++11 && \\\n  cp STAR /usr/local/bin\
      \ && \\\n  cd / && \\\n  rm -rf /tmp/STAR-${STAR_VERSION} /tmp/${STAR_VERSION}.zip\
      \ && \\\n  apt-get --purge autoremove -y ${PACKAGES} && \\\n  apt-get clean\n"
    build_args: []
    env: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    - "highcpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/mapping/star_build_reference/config.vsh.yml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/mapping/star_build_reference"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/mapping/star_build_reference/star_build_reference"
  viash_version: "0.7.0"
  git_commit: "79131063f70d256bcdd4e47f0572f968cc71938b"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
