functionality:
  name: "make_reference"
  namespace: "reference"
  version: "0.7.1"
  authors:
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments:
  - type: "file"
    name: "--genome_fasta"
    alternatives: []
    description: "Reference genome fasta. Example: "
    example:
    - "genome_fasta.fa.gz"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_gtf"
    alternatives: []
    description: "Reference transcriptome annotation."
    example:
    - "transcriptome.gtf.gz"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--ercc"
    alternatives: []
    description: "ERCC sequence and annotation file."
    example:
    - "ercc.zip"
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--subset_regex"
    alternatives: []
    description: "Will subset the reference chromosomes using the given regex."
    example:
    - "(ERCC-00002|chr1)"
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_fasta"
    alternatives: []
    description: "Output genome sequence fasta."
    example:
    - "genome_sequence.fa.gz"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_gtf"
    alternatives: []
    description: "Output transcriptome annotation gtf."
    example:
    - "transcriptome_annotation.gtf.gz"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Preprocess and build a transcriptome reference.\n\nExample input files\
    \ are:\n  - `genome_fasta`: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/GRCh38.primary_assembly.genome.fa.gz\n\
    \  - `transcriptome_gtf`: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz\n\
    \  - `ercc`: https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip\n"
  test_resources:
  - type: "bash_script"
    path: "run_test.sh"
    is_executable: true
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ubuntu:22.04"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "pigz"
    - "seqkit"
    - "curl"
    - "wget"
    - "unzip"
    interactive: false
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    - "highcpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/reference/make_reference/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/reference/make_reference"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/reference/make_reference/make_reference"
  viash_version: "0.7.1"
  git_commit: "a80439cf867ae6259990141dc4596cdcaa26ece6"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
