functionality:
  name: mermaid
  namespace: "report"
  version: "dev"
  description: |
    Generates a network from mermaid code. 
    
    See `https://mermaid-js.github.io/mermaid/#/Tutorials`. 
    This component uses the external mermaid.ink service to generate visual networks.
  authors:
    - __merge__: ../../authors/dries_de_maeyer.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Input directory
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Generated network as output.
      direction: output
      required: true
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - requests
          - Pillow~=9.2.0
    test_setup:
      - type: python
        packages:
          - viashpy
  - type: nextflow
