functionality:
  name: "tar_extract"
  namespace: "compression"
  version: "main_build"
  authors: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input file"
    example:
    - "input.tar.gz"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Folder to restore file(s) to."
    example:
    - "output_folder"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--strip_components"
    alternatives:
    - "-s"
    description: "Strip this amount of leading components from file names on extraction.\
      \ For example, to extract only 'myfile.txt' from an archive containing the structure\
      \ `this/goes/deep/myfile.txt', use 3 to strip 'this/goes/deep/'."
    example:
    - 1
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--exclude"
    alternatives:
    - "-e"
    description: "Prevents any file or member whose name matches the shell wildcard\
      \ (pattern) from being extracted."
    example:
    - "docs/figures"
    default: []
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Extract files from a tar archive"
  test_resources:
  - type: "bash_script"
    path: "run_test.sh"
    is_executable: true
  - type: "file"
    path: "../../../LICENSE"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "native"
  id: "native"
- type: "docker"
  id: "docker"
  image: "ubuntu:latest"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup: []
  test_setup: []
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/compression/tar_extract/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/openpipeline/openpipeline/target/native/compression/tar_extract"
  executable: "/home/runner/work/openpipeline/openpipeline/target/native/compression/tar_extract/tar_extract"
  viash_version: "0.7.0"
  git_commit: "79131063f70d256bcdd4e47f0572f968cc71938b"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
