functionality:
  name: bcl_convert
  namespace: demux
  description: |
    Convert bcl files to fastq files using bcl-convert.
    Information about upgrading from bcl2fastq via
    https://emea.support.illumina.com/bulletins/2020/10/upgrading-from-bcl2fastq-to-bcl-convert.html
    and https://support.illumina.com/sequencing/sequencing_software/bcl-convert/compatibility.html
  authors:
    - __merge__: ../../authors/toni_verbeiren.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../authors/marijke_van_moerbeke.yaml
      roles: [ author ]
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Input run directory
      example: bcl_dir
    - name: "--sample_sheet"
      alternatives: [ "-s" ]
      type: file
      required: true
      description: Pointer to the sample sheet
      example: bcl_dir
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Output directory containig fastq files
      example: fastq_dir
    - name: "--reports"
      type: file
      direction: output
      required: false
      description: Reports directory
      example: reports_dir
    - name: "--test_mode"
      type: boolean
      default: false
      description: Should bcl-convert be run in test mode (using --first-tile-only)?
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: ../../../resources_test/cellranger_tiny_bcl/bcl2
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/bclconvert:3.10
  - type: nextflow
    directives:
      label: [ midmem, midcpu ]
