functionality:
  name: run_cellxgene
  namespace: interactive
  version: 1.0
  description: ""
  arguments:
  - name: "--input"
    alternatives: ["-i"]
    type: file
    description: Directory to mount
    direction: input
    default: ./
  - name: "--port"
    alternatives: ["-p"]
    type: string
    description: Port to use
    default: "5005"
  resources:
    - type: bash_script
      path: script.sh
  # test_resources: 
  #   - type: bash_script
  #     path: run_test.sh
platforms:
  - type: docker
    image: ubuntu:focal
    run_args:
      - "$( echo $VIASH_PAR_PORT | sed 's/..*/-p &:&/' )"
    setup:
      - type: docker
        run: apt update && apt upgrade -y
      - type: apt
        packages:
          - build-essential libxml2-dev python3-dev python3-pip zlib1g-dev python3-requests python3-aiohttp python-is-python3
      - type: python
        packages:
          - cellxgene
