functionality:
  name: concat
  namespace: "dataflow"
  description: |
    Concatenates several uni-modal samples in .h5mu files into a single file.
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      multiple: true
      multiple_sep: ','
      description: Paths to the different samples to be concatenated.
      required: true
      example: sample_paths
    - name: "--input_id"
      type: string
      multiple: true
      multiple_sep: ','
      description: |
        Names of the different samples that have to be concatenated.  Must be specified when using '--mode move'.
        In this case, the ids will be used for the columns names of the dataframes registring the conflicts.
        If specified, must be of same length as `--input`.
      required: false
    - name: "--output"
      alternatives: ["-o"]
      type: file
      direction: output
      example: "output.h5mu"
    - name: "--obs_sample_name"
      type: string
      description: Name of the .obs key under which to add the sample names.
      default: "sample_id"
    - name: "--compression"
      type: string
      description: The compression format to be used on the final h5mu object.
      default: "gzip"
    - name: "--other_axis_mode"
      type: string
      choices: [same, unique, first, only, concat, move]
      default: move
      description: |
        How to handle the merging of other axis (var, obs, ...).

         - None: keep no data
         - same: only keep elements of the matrices which are the same in each of the samples
         - unique: only keep elements for which there is only 1 possible value (1 value that can occur in multiple samples)
         - first: keep the annotation from the first sample
         - only: keep elements that show up in only one of the objects (1 unique element in only 1 sample)
         - move: identical to 'same', but moving the conflicting values to .varm or .obsm
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test_concat.py
    - path: ../../../resources_test/concat_test_data/e18_mouse_brain_fresh_5k_filtered_feature_bc_matrix_subset_unique_obs.h5mu
    - path: ../../../resources_test/concat_test_data/human_brain_3k_filtered_feature_bc_matrix_subset_unique_obs.h5mu
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
    test_setup:
      - type: python
        packages:
          - viashpy
  - type: native
  - type: nextflow
    directives:
      label: [midcpu, highmem]