functionality:
  name: "process_smartseq2"
  namespace: "tabula_sapiens"
  authors:
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: sample
        - type: string
          name: --input_id
          required: true
          description: The ID of the sample being processed. This vector should have the same length as the `--input_r1` argument.
          example: [ mysample, mysample ]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --input_r1
          required: true
          description: Paths to the sequences to be mapped. If using Illumina paired-end reads, only the R1 files should be passed.
          example: [ mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L002_R1_001.fastq.gz ]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --input_r2
          required: false
          description: Paths to the sequences to be mapped. If using Illumina paired-end reads, only the R2 files should be passed.
          example: [ mysample_S1_L001_R2_001.fastq.gz, mysample_S1_L002_R2_001.fastq.gz ]
          multiple: true
          multiple_sep: ";"
        - type: file
          name: --reference_index
          alternatives: --genomeDir
          description: Path to the reference built by star_build_reference. Corresponds to the --genomeDir argument in the STAR command.
          example: /path/to/reference
          required: true
        - type: file
          name: --reference_gtf
          description: Path to the gtf reference file.
          example: genes.gtf
          required: true
        - type: file
          name: --output_raw
          direction: output
          default: '$id.output_raw'
          description: The output h5mu.
        - type: file
          name: --output_h5mu
          direction: output
          default: '$id.output_h5mu.h5mu'
          description: The output h5mu.
  resources:
    - type: nextflow_script
      path: main.nf
  # test_resources:
  #   - type: nextflow_script
  #     path: main.nf
  #     entrypoint: test_wf
platforms:
  - type: nextflow