functionality:
  name: "integration"
  namespace: "multiomics"
  description: "A pipeline for demultiplexing multimodal multi-sample RNA transcriptomics data."
  authors:
    - __merge__: ../../../src/authors/dries_de_maeyer.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author ]
  argument_groups:
    - name: "Inputs"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          required: true
          type: file
          description: Path to the sample.
          example: dataset.h5mu
        - name: "--layer"
          default: "log_normalized"
          type: string
          description: use specified layer for expression values instead of the .X object from the modality.
          required: false
    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
    - name: PCA options
      arguments:
        - name: "--obsm_pca"
          type: string
          default: "X_pca"
          description: "In which .obsm slot to store the resulting PCA embedding."
        - name: "--var_pca_feature_selection"
          type: string
          required: false
          description: Column name in .var matrix that will be used to select which genes to run the PCA on.
    - name: Harmony integration options
      arguments:
        - name: "--obsm_integrated"
          type: string
          default: "X_pca_integrated"
          required: false
          description: "In which .obsm slot to store the resulting integrated embedding."
        - name: "--obs_covariates"
          type: string
          description: "The .obs field(s) that define the covariate(s) to regress out."
          example: ["batch", "sample"]
          multiple: true
          required: true
        - name: "--rna_theta"
          type: double
          description: |
            Diversity clustering penalty parameter. Specify for each variable in group.by.vars. 
            theta=0 does not encourage any diversity. Larger values of theta
            result in more diverse clusters."
          default: 2
          multiple: true
    - name: Neighbour calculation
      arguments:
        - name: "--uns_neighbors"
          type: string
          default: neighbors
          description: In which .uns slot to store various neighbor output objects.
        - name: "--obsp_neighbor_distances"
          type: string
          default: "distances"
          description: "In which .obsp slot to store the distance matrix between the resulting neighbors."
        - name: "--obsp_neighbor_connectivities"
          type: string
          default: "connectivities"
          description: "In which .obsp slot to store the connectivities matrix between the resulting neighbors."
    - name: Clustering options
      arguments:
        - name: "--obs_cluster"
          type: string
          description: Name of the .obs key under which to add the cluster labels.
          default: "leiden"
        - name: "--leiden_resolution"
          type: double
          description: Control the coarseness of the clustering. Higher values lead to more clusters.
          default: 1
    - name: Umap options
      arguments:
        - name: "--obsm_umap"
          type: string
          default: "X_umap"
          required: false
          description: "In which .obsm slot to store the resulting UMAP embedding."

  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: ../../../resources_test/concat_test_data