functionality:
  name: "htseq_count"
  namespace: "mapping"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  arguments: []
  argument_groups:
  - name: "Input"
    arguments:
    - type: "file"
      name: "--input"
      alternatives: []
      description: "Path to the SAM/BAM files containing the mapped reads."
      info:
        orig_arg: "samfilenames"
      example:
      - "mysample1.BAM"
      - "mysample2.BAM"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "file"
      name: "--reference"
      alternatives: []
      description: "Path to the GTF file containing the features."
      info:
        orig_arg: "featurefilename"
      example:
      - "reference.gtf"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      alternatives: []
      description: "Filename to output the counts to."
      info:
        orig_arg: "--counts_output"
      example:
      - "htseq-count.tsv"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_delimiter"
      alternatives: []
      description: "Column delimiter in output."
      info:
        orig_arg: "--delimiter"
      example:
      - "\t"
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--output_sam"
      alternatives: []
      description: "Write out all SAM alignment records into SAM/BAM files (one per\
        \ input file needed), \nannotating each line with its feature assignment (as\
        \ an optional field with tag 'XF'). \nSee the -p option to use BAM instead\
        \ of SAM.\n"
      info:
        orig_arg: "--samout"
      example:
      - "mysample1_out.BAM"
      - "mysample2_out.BAM"
      default: []
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--output_sam_format"
      alternatives: []
      description: "Format to use with the --output_sam argument."
      info:
        orig_arg: "--samout-format"
      example: []
      default: []
      required: false
      choices:
      - "sam"
      - "bam"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Arguments"
    arguments:
    - type: "string"
      name: "--order"
      alternatives:
      - "-r"
      description: "Sorting order of <alignment_file>. Paired-end sequencing data\
        \ must be sorted either by position or\nby read name, and the sorting order\
        \ must be specified. Ignored for single-end data.\n"
      info:
        orig_arg: "--order"
      example: []
      default:
      - "name"
      required: false
      choices:
      - "pos"
      - "name"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--stranded"
      alternatives:
      - "-s"
      description: "Whether the data is from a strand-specific assay. 'reverse' means\
        \ 'yes' with reversed strand interpretation."
      info:
        orig_arg: "--stranded"
      example: []
      default:
      - "yes"
      required: false
      choices:
      - "yes"
      - "no"
      - "reverse"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--minimum_alignment_quality"
      alternatives:
      - "-a"
      - "--minaqual"
      description: "Skip all reads with MAPQ alignment quality lower than the given\
        \ minimum value. \nMAPQ is the 5th column of a SAM/BAM file and its usage\
        \ depends on the software \nused to map the reads.\n"
      info:
        orig_arg: "--minaqual"
      example: []
      default:
      - 10
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--type"
      alternatives:
      - "-t"
      description: "Feature type (3rd column in GTF file) to be used, all features\
        \ of other type are ignored (default, suitable for Ensembl GTF files: exon)"
      info:
        orig_arg: "--type"
      example:
      - "exon"
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--id_attribute"
      alternatives:
      - "-i"
      description: "GTF attribute to be used as feature ID (default, suitable for\
        \ Ensembl GTF files: gene_id).\nAll feature of the right type (see -t option)\
        \ within the same GTF attribute will be added\ntogether. The typical way of\
        \ using this option is to count all exonic reads from each gene\nand add the\
        \ exons but other uses are possible as well. You can call this option multiple\n\
        times: in that case, the combination of all attributes separated by colons\
        \ (:) will be used\nas a unique identifier, e.g. for exons you might use -i\
        \ gene_id -i exon_number.\n"
      info:
        orig_arg: "--idattr"
      example:
      - "gene_id"
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--additional_attributes"
      alternatives: []
      description: "Additional feature attributes (suitable for Ensembl GTF files:\
        \ gene_name). Use multiple times\nfor more than one additional attribute.\
        \ These attributes are only used as annotations in the\noutput, while the\
        \ determination of how the counts are added together is done based on option\
        \ -i.\n"
      info:
        orig_arg: "--additional-attr"
      example:
      - "gene_name"
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--add_chromosome_info"
      alternatives: []
      description: "Store information about the chromosome of each feature as an additional\
        \ attribute\n(e.g. colunm in the TSV output file).\n"
      info:
        orig_arg: "--add-chromosome-info"
      direction: "input"
      dest: "par"
    - type: "string"
      name: "--mode"
      alternatives:
      - "-m"
      description: "Mode to handle reads overlapping more than one feature."
      info:
        orig_arg: "--mode"
      example: []
      default:
      - "union"
      required: false
      choices:
      - "union"
      - "intersection-strict"
      - "intersection-nonempty"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--non_unique"
      alternatives: []
      description: "Whether and how to score reads that are not uniquely aligned or\
        \ ambiguously assigned to features."
      info:
        orig_arg: "--nonunique"
      example: []
      default:
      - "none"
      required: false
      choices:
      - "none"
      - "all"
      - "fraction"
      - "random"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--secondary_alignments"
      alternatives: []
      description: "Whether to score secondary alignments (0x100 flag)."
      info:
        orig_arg: "--secondary-alignments"
      example: []
      default: []
      required: false
      choices:
      - "score"
      - "ignore"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--supplementary_alignments"
      alternatives: []
      description: "Whether to score supplementary alignments (0x800 flag)."
      info:
        orig_arg: "--supplementary-alignments"
      example: []
      default: []
      required: false
      choices:
      - "score"
      - "ignore"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--counts_output_sparse"
      alternatives: []
      description: "Store the counts as a sparse matrix (mtx, h5ad, loom)."
      info:
        orig_arg: "--counts-output-sparse"
      direction: "input"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Quantify gene expression for subsequent testing for differential expression.\n\
    \nThis script takes one or more alignment files in SAM/BAM format and a feature\
    \ file in GFF format and calculates for each feature the number of reads mapping\
    \ to it. \n\nSee http://htseq.readthedocs.io/en/master/count.html for details.\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/cellranger_tiny_fastq"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "HTSeq"
    - "pyyaml"
    - "scipy"
    - "anndata~=0.8.0"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "highmem"
    - "highcpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/mapping/htseq_count/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/mapping/htseq_count"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/mapping/htseq_count/htseq_count"
  viash_version: "0.7.1"
  git_commit: "275ed3f9481a5183da75c603edd18436aee5daa4"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
