functionality:
  name: pca
  namespace: "dimred"
  version: "dev"
  description: |
    Computes PCA coordinates, loadings and variance decomposition. Uses the implementation of scikit-learn [Pedregosa11].
  authors:
    - __merge__: ../../authors/dries_de_maeyer.yaml
      roles: [ maintainer ]
  arguments:
    # inputs
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file
      direction: input
      required: true
      example: input.h5mu

    - name: "--modality"
      type: string
      default: "rna"
      required: false

    - name: "--layer"
      type: string
      description: Use specified layer for expression values instead of the .X object from the modality.
      required: false

    - name: "--var_input"
      type: string
      description: Column name in .var matrix that will be used to select which genes to run the PCA on.
      example: filter_with_hvg

    # outputs
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      direction: output
      required: true
      example: output.h5mu

    - name: "--obsm_output"
      type: string
      default: "X_pca"
      description: "In which .obsm slot to store the resulting embedding."

    - name: "--varm_output"
      type: string
      default: "pca_loadings"
      description: "In which .varm slot to store the resulting loadings matrix."

    - name: "--uns_output"
      type: string
      default: "pca_variance"
      description: "In which .uns slot to store the resulting variance objects."
    
    # arguments
    - name: "--num_components"
      type: integer
      example: 25
      description: Number of principal components to compute. Defaults to 50, or 1 - minimum dimension size of selected representation.

    - name: "--overwrite"
      type: boolean_true
      description: "Allow overwriting .obsm, .varm and .uns slots."
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: python
        packages:
          - scanpy~=1.9.2
          - mudata~=0.2.0
          - anndata~=0.8.0
    test_setup:
      - type: python
        packages: 
          - viashpy
  - type: nextflow
    directives:
      label: highcpu
