#!/bin/sh

if [ ${#} -lt 1 ]; then
  echo "Usage: ${0} <job file>"
  exit 1
fi

script_base=`echo $(basename $1) | rev | cut -f 2- -d '.' | rev`

for job in `aegea batch ls --status FAILED -c jobId | grep "minutes ago" | cut -c 2-37 | grep -a "-"`
    do echo ${job}
    job_description=`aegea batch describe ${job}`
    partition=`echo ${job_description} | grep "partition_id" | sed -e 's/.*\(partition_id [0-9]*\).*/\1/'`
    exp_id=`echo ${job_description} | grep "partition_id" | sed -e 's/.*\(--input_dirs [0-9A-Za-z_]*\).*/\1/'`
    echo "${partition} ${exp_id}" >> ${script_base}_failed_jobs
done

if [ -f ${script_base}_failed_jobs ]
then
    grep -f ${script_base}_failed_jobs $1 | awk '{print $0, "\nsleep 20"}' > ${script_base}_failed_jobs.sh
    rm ${script_base}_failed_jobs
else
    echo "looks like nothing failed!"
fi
