functionality:
  name: leiden
  namespace: "cluster"
  description: |
    Cluster cells using the Leiden algorithm [Traag18] implemented in the Scanpy framework [Wolf18]. 
    Leiden is an improved version of the Louvain algorithm [Blondel08]. 
    It has been proposed for single-cell analysis by [Levine15]. 
    This requires having ran `neighbors/find_neighbors` or `neighbors/bbknn` first.

    Blondel08: Blondel et al. (2008), Fast unfolding of communities in large networks, J. Stat. Mech.  
    Levine15: Levine et al. (2015), Data-Driven Phenotypic Dissection of AML Reveals Progenitor-like Cells that Correlate with Prognosis, Cell.  
    Traag18: Traag et al. (2018), From Louvain to Leiden: guaranteeing well-connected communities arXiv.  
    Wolf18: Wolf et al. (2018), Scanpy: large-scale single-cell gene expression data analysis, Genome Biology.  
  authors:
    - __merge__: ../../authors/dries_de_maeyer.yaml
      roles: [ maintainer ]
  arguments:
    # input
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Input file.
      direction: input
      required: true
      example: input.h5mu

    - name: "--modality"
      type: string
      default: "rna"
      required: false

    - name: "--obsp_connectivities"
      type: string
      description: In which .obsp slot the neighbor connectivities can be found.
      default: "connectivities"

    # output
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output file.
      direction: output
      required: true
      example: output.h5mu

    - name: "--obs_name"
      type: string
      description: Name of the .obs key under which to add the cluster labels.
      default: "leiden"

      # todo: add uns_params
      # example: uns["leiden"] = {'params': {'n_iterations': -1, 'random_state': 0, 'resolution': 1.0}}

    # arguments
    - name: "--resolution"
      type: double
      description: A parameter value controlling the coarseness of the clustering. Higher values lead to more clusters.
      default: 1
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: apt
        packages: [ cmake ]
      - type: python
        packages:
          - scanpy~=1.9.2
          - leidenalg~=0.8.9
          - mudata~=0.2.0
          - anndata~=0.8.0
  - type: nextflow
    directives:
      label: highcpu
