functionality:
  name: scvelo
  namespace: "velocity"
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          direction: input
          description: "Velocyto loom file."
          required: true
    - name: Outputs
      arguments:
        - name: "--output"
          required: true
          type: file
          direction: output
          description: "Output directory. If it does not exist, will be created."
    - name: "Filtering and normalization"
      description: Arguments for filtering, normalization an log transform (see scvelo.pp.filter_and_normalize function)
      arguments:
        - name: --min_counts
          description: Minimum number of counts required for a gene to pass filtering (spliced).
          type: integer
        - name: --min_counts_u
          description: Minimum number of counts required for a gene to pass filtering (unspliced).
          type: integer
        - name: --min_cells
          description: Minimum number of cells expressed required to pass filtering (spliced).
          type: integer
        - name: --min_cells_u
          description: Minimum number of cells expressed required to pass filtering (unspliced).
          type: integer
        - name: "--min_shared_counts"
          description: "Minimum number of counts (both unspliced and spliced) required for a gene."
          type: integer
        - name: "--min_shared_cells"
          description: "Minimum number of cells required to be expressed (both unspliced and spliced)."
          type: integer
        - name: "--n_top_genes"
          description: "Number of genes to keep."
          type: integer
        - name: "--log_transform"
          type: boolean
          default: true
          description: "Do not log transform counts."
    - name: Fitting parameters
      description: Arguments for fitting the data
      arguments:
        - name: --n_principal_components
          description: Number of principal components to use for calculating moments.
          type: integer
        - name: --n_neighbors
          description: |
            Number of neighbors to use. First/second-order moments are computed for each
            cell across its nearest neighbors, where the neighbor graph is obtained from
            euclidean distances in PCA space.
          type: integer
          default: 30
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/rna_velocity/velocyto_processed/cellranger_tiny.loom
platforms:
  - type: docker
    image: python:3.9
    setup:
      - type: python
        pip:
          - scvelo
          - mudata
          - anndata<0.8
  - type: native
  - type: nextflow
    directives:
      label: [ highmem, highcpu ]