functionality:
  name: "spaceranger_mkfastq"
  namespace: "demux"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--input"
    description: "Path to the untarred BCL files."
    example:
    - "/path/to/bcl"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--sample_sheet"
    description: "The path to the sample sheet."
    example:
    - "SampleSheet.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "The folder to store the demux results"
    example:
    - "/path/to/output"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Demultiplex raw sequencing data"
  usage: "spaceranger mkfastq --input /path/to/bcl --sample_sheet \\\n  sample_sheet.csv\
    \ --output fastqs --reports reports\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/spaceranger:latest"
  target_organization: "czbiohub"
  target_registry: "docker.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/czbiohub/utilities"
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/utilities/utilities/src/demux/spaceranger_mkfastq/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/utilities/utilities/target/native/demux/spaceranger_mkfastq"
  executable: "/home/runner/work/utilities/utilities/target/native/demux/spaceranger_mkfastq/spaceranger_mkfastq"
  viash_version: "0.7.3"
  git_commit: "54b6322faa244e2d61d6397b2f3dd02709fe25df"
  git_remote: "https://github.com/czbiohub/utilities"
