functionality:
  name: "cellbender_remove_background"
  namespace: "correction"
  version: "main_build"
  authors: []
  arguments: []
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--input"
      alternatives:
      - "-i"
      description: "Input h5mu file."
      example:
      - "input.h5mu"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      alternatives: []
      description: "List of modalities to process."
      example: []
      default:
      - "rna"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      alternatives:
      - "-o"
      description: "Full count matrix as an h5mu file, with background RNA removed.\
        \ This file contains all the original droplet barcodes."
      example:
      - "output.h5mu"
      default: []
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      alternatives: []
      example:
      - "gzip"
      default: []
      required: false
      choices:
      - "gzip"
      - "lzf"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--layer_output"
      alternatives: []
      description: "Output layer"
      example: []
      default:
      - "corrected"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_latent_rt_efficiency"
      alternatives: []
      example: []
      default:
      - "latent_rt_efficiency"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_latent_cell_probability"
      alternatives: []
      example: []
      default:
      - "latent_cell_probability"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_latent_scale"
      alternatives: []
      example: []
      default:
      - "latent_scale"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--var_ambient_expression"
      alternatives: []
      example: []
      default:
      - "ambient_expression"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_latent_gene_encoding"
      alternatives: []
      example: []
      default:
      - "cellbender_latent_gene_encoding"
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Arguments"
    arguments:
    - type: "integer"
      name: "--expected_cells"
      alternatives: []
      description: "Number of cells expected in the dataset (a rough estimate within\
        \ a factor of 2 is sufficient)."
      example:
      - 1000
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--total_droplets_included"
      alternatives: []
      description: "The number of droplets from the rank-ordered UMI plot\nthat will\
        \ be analyzed. The largest 'total_droplets'\ndroplets will have their cell\
        \ probabilities inferred\nas an output.\n"
      example:
      - 25000
      default: []
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--expected_cells_from_qc"
      alternatives: []
      description: "Will use the Cell Ranger QC to determine the estimated number\
        \ of cells"
      example: []
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--model"
      alternatives: []
      description: "Which model is being used for count data. 'simple'\ndoes not model\
        \ either ambient RNA or random barcode\nswapping (for debugging purposes --\
        \ not recommended).\n'ambient' assumes background RNA is incorporated into\n\
        droplets. 'swapping' assumes background RNA comes from\nrandom barcode swapping.\
        \ 'full' uses a combined\nambient and swapping model.\n"
      example: []
      default:
      - "full"
      required: false
      choices:
      - "simple"
      - "ambient"
      - "swapping"
      - "full"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--epochs"
      alternatives: []
      description: "Number of epochs to train."
      example: []
      default:
      - 150
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--low_count_threshold"
      alternatives: []
      description: "Droplets with UMI counts below this number are completely \nexcluded\
        \ from the analysis. This can help identify the correct \nprior for empty\
        \ droplet counts in the rare case where empty \ncounts are extremely high\
        \ (over 200).\n"
      example: []
      default:
      - 15
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--z_dim"
      alternatives: []
      description: "Dimension of latent variable z.\n"
      example: []
      default:
      - 100
      required: false
      choices: []
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--z_layers"
      alternatives: []
      description: "Dimension of hidden layers in the encoder for z.\n"
      example: []
      default:
      - 500
      required: false
      choices: []
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--training_fraction"
      alternatives: []
      description: "Training detail: the fraction of the data used for training.\n\
        The rest is never seen by the inference algorithm. Speeds up learning.\n"
      example: []
      default:
      - 0.9
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--empty_drop_training_fraction"
      alternatives: []
      description: "Training detail: the fraction of the training data each epoch\
        \ that \nis drawn (randomly sampled) from surely empty droplets.\n"
      example: []
      default:
      - 0.5
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--fpr"
      alternatives: []
      description: "Target false positive rate in (0, 1). A false positive\nis a true\
        \ signal count that is erroneously removed.\nMore background removal is accompanied\
        \ by more signal\nremoval at high values of FPR. You can specify\nmultiple\
        \ values, which will create multiple output\nfiles.\n"
      example: []
      default:
      - 0.01
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--exclude_antibody_capture"
      alternatives: []
      description: "Including the flag --exclude-antibody-capture will\ncause remove-background\
        \ to operate on gene counts\nonly, ignoring other features.\n"
      direction: "input"
      dest: "par"
    - type: "double"
      name: "--learning_rate"
      alternatives: []
      description: "Training detail: lower learning rate for inference. A\nOneCycle\
        \ learning rate schedule is used, where the\nupper learning rate is ten times\
        \ this value. (For this\nvalue, probably do not exceed 1e-3).\n"
      example:
      - 1.0E-4
      default: []
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean_true"
      name: "--cuda"
      alternatives: []
      description: "Including the flag --cuda will run the inference on a\nGPU.\n"
      direction: "input"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "helper.py"
  description: "Eliminating technical artifacts from high-throughput single-cell RNA\
    \ sequencing data.\n\nThis module removes counts due to ambient RNA molecules\
    \ and random barcode swapping from (raw) UMI-based scRNA-seq count matrices. \n\
    At the moment, only the count matrices produced by the CellRanger count pipeline\
    \ is supported. Support for additional tools and protocols \nwill be added in\
    \ the future. A quick start tutorial can be found here.\n\nFleming et al. 2022,\
    \ bioRxiv.\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_raw_feature_bc_matrix.h5"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/pytorch:22.12-py3"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    label: []
    add: []
    copy: []
    run: []
    build_args: []
    env:
    - "SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL True"
  - type: "apt"
    packages:
    - "git"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "anndata~=0.8.0"
    - "mudata~=0.2.0"
    pip: []
    pypi: []
    git: []
    github:
    - "broadinstitute/CellBender"
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup:
  - type: "python"
    user: false
    packages:
    - "muon"
    - "scanpy~=1.9.2"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "gpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/correction/cellbender_remove_background/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/correction/cellbender_remove_background"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/correction/cellbender_remove_background/cellbender_remove_background"
  viash_version: "0.7.1"
  git_commit: "275ed3f9481a5183da75c603edd18436aee5daa4"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
