functionality:
  name: "prot_multisample"
  namespace: "multiomics"
  description: "Processing unimodal multi-sample ADT data."
  authors:
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author ]
  argument_groups:
    - name: "Inputs"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the concatenated file
          example: concatenated
        - name: "--sample_id"
          required: true
          type: string
          multiple_sep: ';'
          multiple: true
          description: IDs of the sample.
          example: foo
        - name: "--input"
          required: true
          type: file
          multiple_sep: ';'
          multiple: true
          description: Path to the samples.
          example: dataset.h5mu
    - name: "Sample ID options"
      description: |
        Options for adding the id to .obs on the MuData object. Having a sample 
        id present in a requirement of several components for this pipeline.
      arguments:
        - name: "--add_id_to_obs"
          description: "Add the value passed with --id to .obs."
          type: boolean
          default: true
        - name: --add_id_obs_output
          description: |
            .Obs column to add the sample IDs to. Required and only used when 
            --add_id_to_obs is set to 'true'
          type: string
          default: "sample_id"
        - name: "--add_id_make_observation_keys_unique"
          type: boolean
          description: |
            Join the id to the .obs index (.obs_names). 
            Only used when --add_id_to_obs is set to 'true'.
          default: true
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: ../../../resources_test/pbmc_1k_protein_v3