functionality:
  name: "spaceranger_count"
  namespace: "mapping"
  version: "0.1.3"
  arguments:
  - type: "file"
    name: "--input_fastqs"
    description: "Path to the fastq files."
    example:
    - "/path/to/bcl"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--input_tif"
    description: "Path to the tif file"
    example:
    - "path/to/tif"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--reference_genome"
    description: "Path to the reference genome"
    example:
    - "path/to/ref_genome"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "The name of the folder to store the results in"
    default:
    - "outs"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--id"
    description: "ID name for temporary output directory."
    default:
    - "output"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--sample"
    description: "Sample name to analyze."
    example:
    - "test_sample"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--lanes"
    description: "Lanes associated with this sample."
    example:
    - 1
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--slide"
    description: "Slide associated with this sample."
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Align fastqs and detect tissues"
  usage: "spaceranger count --input /path/to/bcl --sample \\\n  test_sample --id 13423\
    \ --lanes 1\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/spaceranger:latest"
  target_organization: "czbiohub"
  target_registry: "docker.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/czbiohub/utilities"
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/utilities/utilities/src/mapping/spaceranger_count/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/utilities/utilities/target/nextflow/mapping/spaceranger_count"
  executable: "/home/runner/work/utilities/utilities/target/nextflow/mapping/spaceranger_count/spaceranger_count"
  viash_version: "0.7.3"
  git_commit: "0120a8e813499e4a6c690a375ba663aea07fca8a"
  git_remote: "https://github.com/czbiohub/utilities"
