#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser()

parser.add_argument('taxon', choices=('mus', 'homo'))
parser.add_argument('num_partitions', type=int)
parser.add_argument('exp_ids', nargs='+')
parser.add_argument('script_args', nargs=argparse.REMAINDER,
                    help='Other args passed to run_star_and_htseq')

args = parser.parse_args()

for i in range(args.num_partitions):
    print(' '.join(('evros',
                    'alignment.run_star_and_htseq',
                    '--taxon {}'.format(args.taxon),
                    '--num_partitions {}'.format(args.num_partitions),
                    '--partition_id {}'.format(i),
                    '--exp_ids {}'.format(' '.join(args.exp_ids)),
                    ' '.join(args.script_args)))
          )
    print('sleep 10')
