#!/bin/sh
if [ $# -lt 1 ]; then
  echo "Usage: $0 <job file>"
  exit 1
fi

for job in `aegea batch ls --status FAILED -c jobId | grep "minutes ago" | cut -c 2-37 | grep -a "-"`
    do echo $job
    aegea batch describe $job | grep "partition_id" | sed -e 's/.*\(partition_id [0-9]*\).*/\1/' >> ${1}_failed_jobs
done

if [ -f ${1}_failed_jobs ]
then
    grep -f ${1}_failed_jobs $1 | awk '{print $0, "\nsleep 20"}' > ${1}_failed_jobs.sh
    rm ${1}_failed_jobs
else
    echo "looks like nothing failed!"
fi
