functionality:
  name: "cellranger_postprocessing"
  namespace: "ingestion"
  description: "Post-processing Cell Ranger datasets."
  info:
    name: Cell Ranger post-processing
  authors:
    - __merge__: ../../../src/authors/angela_pisco.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - type: file
          name: --input
          required: true
          example: "input.h5mu"
          description: Input h5mu file created by running Cell Ranger and converting its output to h5mu.
    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          direction: output
          description: "The converted h5mu file."
    - name: Correction arguments
      arguments:
        - name: "--perform_correction"
          type: boolean_true
          description: Whether or not to run CellBender to perform count correction.
    - name: Filtering arguments
      arguments:
        - name: "--min_genes"
          type: integer
          example: 100
          description: Minimum number of counts required for a cell to pass filtering.
        - name: "--min_counts"
          type: integer
          example: 1000
          description: Minimum number of genes expressed required for a cell to pass filtering.
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: ../../../resources_test/pbmc_1k_protein_v3
