functionality:
  name: make_reference
  namespace: ingestion
  description: |
    Build a transcriptomics reference into one of many formats.
  authors:
    - __merge__: ../../../src/authors/angela_pisco.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the reference.
          example: foo
        - type: file
          name: --genome_fasta
          required: true
          description: Reference genome fasta.
          example: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/GRCh38.primary_assembly.genome.fa.gz
        - type: file
          name: --transcriptome_gtf
          required: true
          description: Reference transcriptome annotation.
          example: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz
        - type: file
          name: --ercc
          description: ERCC sequence and annotation file.
          example: https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip
    - name: Outputs
      arguments:
        - type: string
          name: --target
          choices: [ cellranger, bd_rhapsody, star ]
          description: Which reference indices to generate. 
          multiple: true
          default: [ star ]
        - type: file
          name: --output_fasta
          direction: output
          description: Output genome sequence fasta.
          example: genome_sequence.fa.gz
        - type: file
          name: --output_gtf
          direction: output
          description: Output transcriptome annotation gtf.
          example: transcriptome_annotation.gtf.gz
        - type: file
          name: --output_cellranger
          direction: output
          description: Output index
          example: cellranger_index.tar.gz
        - type: file
          name: --output_bd_rhapsody
          direction: output
          description: Output index
          example: bdrhap_index.tar.gz
        - type: file
          name: --output_star
          direction: output
          description: Output index
          example: star_index.tar.gz
    - name: Arguments
      arguments:
        - type: string
          name: --subset_regex
          description: Will subset the reference chromosomes using the given regex.
          example: (ERCC-00002|chr1)
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
