functionality:
  name: "velocyto_to_h5mu"
  namespace: "convert"
  description: |
    Convert a velocyto loom file to a h5mu file.

    If an input h5mu file is also provided, the velocity
    h5ad object will get added to that h5mu instead.
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer, author ]
    - __merge__: ../../authors/robrecht_cannoodt.yaml
      roles: [ author ]
    - __merge__: ../../authors/angela_pisco.yaml
      roles: [ contributor ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input_loom"
          type: file
          description: Path to the input loom file.
          example: input.loom
          required: true
        - name: "--input_h5mu"
          type: file
          description: If a MuData file is provided, 
          example: input.h5mu
        - name: "--modality"
          type: string
          description: The name of the modality to operate on.
          default: rna_velocity
    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          description: Path to the output MuData file.
          example: output.h5mu
          direction: output
        - name: "--layer_spliced"
          type: string
          description: Output layer for the spliced reads.
          default: velo_spliced
        - name: "--layer_unspliced"
          type: string
          description: Output layer for the unspliced reads.
          default: velo_unspliced
        - name: "--layer_ambiguous"
          type: string
          description: Output layer for the ambiguous reads.
          default: velo_ambiguous
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/cellranger_tiny_fastq
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages: 
          - mudata~=0.2.0
          - anndata~=0.8
          - scanpy~=1.9.2
          - loompy
  - type: nextflow