functionality:
  name: "concat"
  namespace: "tabula_sapiens"
  version: "main_build"
  authors:
  - name: "Angela Pisco"
    roles:
    - "author"
    props:
      github: "aopisco"
      orcid: "0000-0003-0142-2355"
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "string"
      name: "--id"
      description: "ID of the sample."
      example:
      - "sample"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      example:
      - "input.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input_metadata"
      description: "Metadata to be joined to the .obs."
      example:
      - "metadata.csv"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output parameters"
    arguments:
    - type: "file"
      name: "--output"
      description: "The path to the combined h5mu output file."
      default:
      - "$id.output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/utilities/utilities/src/tabula_sapiens/concat/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/utilities/utilities/target/nextflow/tabula_sapiens/concat"
  executable: "/home/runner/work/utilities/utilities/target/nextflow/tabula_sapiens/concat/concat"
  viash_version: "0.7.3"
  git_commit: "e0004bc9c9a0ce5636df28b48a837a4459023711"
  git_remote: "https://github.com/czbiohub/utilities"
