functionality:
  name: split_modalities
  namespace: "dataflow"
  description: |
    Split the modalities from a single .h5mu multimodal sample into seperate .h5mu files. 
  authors:
    - __merge__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
    - __merge__: ../../authors/robrecht_cannoodt.yaml
      roles: [ contributor ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Path to a single .h5mu file.
      required: true
      default: sample_path
    - name: "--output"
      alternatives: ["-o"]
      type: file
      required: true
      direction: output
      example: "/path/to/output"
      description: Output directory containing multiple h5mu files.
    - name: "--output_compression"
      type: string
      description: The compression format to be used on the output h5mu object.
      choices: ["gzip", "lzf"]
      required: false
      example: "gzip"
    - name: "--output_types"
      type: file
      required: true
      direction: output
      example: types.csv
      description: A csv containing the base filename and modality type per output file.
    - name: "--compression"
      type: string
      description: The compression format to be used on the final h5mu object.
      default: "gzip"
  resources:
    - type: python_script
      path: ./script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5mu
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
  - type: native
  - type: nextflow
