project:
  type: website

website:
  title: "CZBiohub/utilities"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - modules/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



