functionality:
  name: "from_h5mu_to_seurat"
  # MuDataSeurat is currently broken -- https://github.com/PMBio/MuDataSeurat/issues/9
  status: disabled 
  namespace: "convert"
  version: "dev"
  description: |
    Converts an h5mu file into a Seurat file.

    Restrictions:
      - Only the intersection of cells is currently loaded into the Seurat object due to the object structure limitation.
      - Multimodal embeddings (global .obsm slot) are loaded with the assay.used field set to the default assay.
      - Embeddings names are changed in order to comply with R & Seurat requirements and conventions.
      - Feature names with underscores ('_') are automatically replaced with dashes ('-')
      - Seurat does not support global variables metadata /var.
  authors:
    - __merge__: ../../authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file
      direction: input
      required: true
      example: input.h5mu
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output Seurat file
      direction: output
      required: true
      example: output.rds
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: r_script
      path: run_test.R
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: docker
        run: apt update && apt upgrade -y
      - type: apt
        packages: 
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python-is-python3
      - type: python
        packages: 
          - scanpy~=1.9.2
          - anndata~=0.8.0
      - type: r
        cran: [ anndata, hdf5r, testthat ]
      - type: r
        github: pmbio/MuDataSeurat
  - type: nextflow
