functionality:
  name: htseq_count_to_h5mu
  namespace: mapping
  description: |
    Convert the htseq table to a h5mu.
  authors:
    - __merge__: ../../authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../authors/angela_pisco.yaml
      roles: [ author ]
  argument_groups:
    - name: Input
      arguments:
        - type: string
          name: --input_id
          required: true
          description: The obs index for the counts
          example: foo
          multiple: true
          multiple_sep: ;
        - type: file
          name: --input_counts
          required: true
          description: The counts as a TSV file as output by HTSeq.
          example: counts.tsv
          multiple: true
          multiple_sep: ;
        - type: file
          name: --reference
          required: true
          description: The GTF file.
          example: gencode_v41_star
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: [-o]
          direction: output
          type: file
          description: "Output h5mu file."
          required: true
          example: output.h5mu
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/cellranger_tiny_fastq
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - anndata~=0.8.0
          - mudata~=0.2.0
          - gtfparse
          - polars[pyarrow]
  - type: nextflow
    directives:
      label: [ highmem, midcpu ]