functionality:
  name: "bcl_convert"
  namespace: "demux"
  version: "main_build"
  authors:
  - name: "Toni Verbeiren"
    roles:
    - "author"
    - "maintainer"
    props:
      github: "tverbeiren"
  - name: "Marijke Van Moerbeke"
    roles:
    - "author"
    props:
      orcid: "0000-0002-3097-5621"
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    description: "Input run directory"
    example:
    - "bcl_dir"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--sample_sheet"
    alternatives:
    - "-s"
    description: "Pointer to the sample sheet"
    example:
    - "bcl_dir"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    description: "Output directory containig fastq files"
    example:
    - "fastq_dir"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--reports"
    alternatives: []
    description: "Reports directory"
    example:
    - "reports_dir"
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--test_mode"
    alternatives: []
    description: "Should bcl-convert be run in test mode (using --first-tile-only)?"
    example: []
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Convert bcl files to fastq files using bcl-convert.\nInformation about\
    \ upgrading from bcl2fastq via\nhttps://emea.support.illumina.com/bulletins/2020/10/upgrading-from-bcl2fastq-to-bcl-convert.html\n\
    and https://support.illumina.com/sequencing/sequencing_software/bcl-convert/compatibility.html\n"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/cellranger_tiny_bcl/bcl2"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/bclconvert:3.10"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label:
    - "midmem"
    - "midcpu"
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/demux/bcl_convert/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/demux/bcl_convert"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/demux/bcl_convert/bcl_convert"
  viash_version: "0.7.1"
  git_commit: "f2e21f1f2d74edac46fca1d608976ca77ca65d0f"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
