---
title: "Log1p"
namespace: "Transform"
description: "Logarithmize the data matrix."
toc: false
---

::: {.column-margin}

### Info

ID: `log1p`  
Namespace: `transform`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/transform/log1p){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Computes X = log(X + 1), where log denotes the natural logarithm unless a different base is given

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script target/nextflow/transform/log1p/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "input.h5mu"
modality: "rna"
# input_layer: "foo"
# output_layer: "foo"
# output: "$id.$key.output.h5mu"
# base: 2

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script target/nextflow/transform/log1p/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name             |Description                                  |Attributes                                 |
|:----------------|:--------------------------------------------|:------------------------------------------|
|`--input`        |Input h5mu file                              |`file`, required, example: `"input.h5mu"`  |
|`--input_layer`  |Input layer to use. If None, X is normalized |`string`                                   |
|`--output_layer` |Output layer to use. By default, use X.      |`string`                                   |
|`--output`       |Output h5mu file.                            |`file`, required, default: `"output.h5mu"` |

## Authors

  * Dries De Maeyer [{{< fa brands github >}}](https://github.com/ddemaeyer) (maintainer)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (contributor)
