---
title: "Cellranger cite seq"
toc: false
---

::: {.column-margin}

### Info

ID: `cellranger_cite_seq`  
Namespace: `multiomics`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/multiomics/cellranger_cite_seq){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Run cite-seq using cellranger count

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.5.1 -latest \
  -main-script target/nextflow/multiomics/cellranger_cite_seq/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r 0.5.1 -latest \
  -profile docker \
  -main-script target/nextflow/multiomics/cellranger_cite_seq/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                 |Description                                  |Attributes                                               |
|:--------------------|:--------------------------------------------|:--------------------------------------------------------|
|`--libraries_path`   |Path to the libraries                        |`file`, required, example: `"/path/to/libraries"`        |
|`--reference_genome` |Path to the reference genome                 |`file`, required, example: `"/path/to/reference_genome"` |
|`--output`           |Path to the output directory                 |`file`, required, example: `"/path/to/directory"`        |
|`--run_id`           |The run ID                                   |`string`, required                                       |
|`--peaks`            |Path to the bed file to use for peak calling |`file`, example: `"/path/to/bed"`                        |
|`--neurips`          |Unknown                                      |`boolean`, default: `FALSE`                              |

## Authors

