---
title: "Scvi"
namespace: "Integrate"
description: "Performs scvi integration as done in the human lung cell atlas https://github.com/LungCellAtlas/HLCA"
toc: false
---

::: {.column-margin}

### Info

ID: `scvi`  
Namespace: `integrate`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/integrate/scvi){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script target/nextflow/integrate/scvi/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
input: # please fill in - example: "path/to/file"
modality: "rna"
# input_layer: "foo"
obs_batch: "sample_id"
# var_input: "foo"

# Outputs
# output: "$id.$key.output.output"
obsm_output: "X_scvi_integrated"

# Early stopping arguments
# early_stopping: true
early_stopping_monitor: "elbo_validation"
early_stopping_patience: 45
early_stopping_min_delta: 0.0

# Learning parameters
max_epochs: # please fill in - example: 123
reduce_lr_on_plateau: true
lr_factor: 0.6
lr_patience: 30

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script target/nextflow/integrate/scvi/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name            |Description                                                                    |Attributes                       |
|:---------------|:------------------------------------------------------------------------------|:--------------------------------|
|`--input`       |Input h5mu file                                                                |`file`, required                 |
|`--input_layer` |Input layer to use. If None, X is used                                         |`string`                         |
|`--obs_batch`   |Column name discriminating between your batches.                               |`string`, default: `"sample_id"` |
|`--var_input`   |.var column containing highly variable genes. By default, do not subset genes. |`string`                         |


### Outputs

|Name            |Description                                                      |Attributes                               |
|:---------------|:----------------------------------------------------------------|:----------------------------------------|
|`--output`      |Output h5mu file.                                                |`file`, required                         |
|`--obsm_output` |In which .obsm slot to store the resulting integrated embedding. |`string`, default: `"X_scvi_integrated"` |


### Early stopping arguments

|Name                         |Description                                                                                                                                          |Attributes                             |
|:----------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------|
|`--early_stopping`           |Whether to perform early stopping with respect to the validation set.                                                                                |`boolean`                              |
|`--early_stopping_monitor`   |Metric logged during validation set epoch.                                                                                                           |`string`, default: `"elbo_validation"` |
|`--early_stopping_patience`  |Number of validation epochs with no improvement after which training will be stopped.                                                                |`integer`, default: `45`               |
|`--early_stopping_min_delta` |Minimum change in the monitored quantity to qualify as an improvement, i.e. an absolute change of less than min_delta, will count as no improvement. |`double`, default: `0`                 |


### Learning parameters

|Name                     |Description                                                                                                      |Attributes                 |
|:------------------------|:----------------------------------------------------------------------------------------------------------------|:--------------------------|
|`--max_epochs`           |Number of passes through the dataset, defaults to (20000 / number of cells) * 400 or 400; whichever is smallest. |`integer`, required        |
|`--reduce_lr_on_plateau` |Whether to monitor validation loss and reduce learning rate when validation set `lr_scheduler_metric` plateaus.  |`boolean`, default: `TRUE` |
|`--lr_factor`            |Factor to reduce learning rate.                                                                                  |`double`, default: `0.6`   |
|`--lr_patience`          |Number of epochs with no improvement after which learning rate will be reduced.                                  |`double`, default: `30`    |

## Authors

  * Malte D. Luecken [{{< fa brands github >}}](https://github.com/LuckyMD) [{{< fa brands orcid >}}](https://orcid.org/0000-0001-7464-7921) (author)
  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (maintainer)
