---
title: "Bbknn"
namespace: "Neighbors"
description: "BBKNN network generation"
toc: false
---

::: {.column-margin}

### Info

ID: `bbknn`  
Namespace: `neighbors`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/neighbors/bbknn){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script target/nextflow/neighbors/bbknn/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
# input: "path/to/file"
modality: "rna"
obsm_input: "X_pca"
obs_batch: "batch"
# output: "$id.$key.output.output"
uns_output: "neighbors"
obsp_distances: "distances"
obsp_connectivities: "connectivities"
n_neighbors_within_batch: 3
n_pcs: 50
# n_trim: 123

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script target/nextflow/neighbors/bbknn/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                         |Description                                                                                                                                                                                                                                                                                                                                                                                                       |Attributes                            |
|:----------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------|
|`--input`                    |Input h5mu file                                                                                                                                                                                                                                                                                                                                                                                                   |`file`                                |
|`--obsm_input`               |The dimensionality reduction in `.obsm` to use for neighbour detection. Defaults to X_pca.                                                                                                                                                                                                                                                                                                                        |`string`, default: `"X_pca"`          |
|`--obs_batch`                |.obs column name discriminating between your batches.                                                                                                                                                                                                                                                                                                                                                             |`string`, default: `"batch"`          |
|`--output`                   |Output .h5mu file.                                                                                                                                                                                                                                                                                                                                                                                                |`file`, required                      |
|`--uns_output`               |Mandatory .uns slot to store various neighbor output objects.                                                                                                                                                                                                                                                                                                                                                     |`string`, default: `"neighbors"`      |
|`--obsp_distances`           |In which .obsp slot to store the distance matrix between the resulting neighbors.                                                                                                                                                                                                                                                                                                                                 |`string`, default: `"distances"`      |
|`--obsp_connectivities`      |In which .obsp slot to store the connectivities matrix between the resulting neighbors.                                                                                                                                                                                                                                                                                                                           |`string`, default: `"connectivities"` |
|`--n_neighbors_within_batch` |How many top neighbours to report for each batch; total number of neighbours in the initial k-nearest-neighbours computation will be this number times the number of batches.                                                                                                                                                                                                                                     |`integer`, default: `3`               |
|`--n_pcs`                    |How many dimensions (in case of PCA, principal components) to use in the analysis.                                                                                                                                                                                                                                                                                                                                |`integer`, default: `50`              |
|`--n_trim`                   |Trim the neighbours of each cell to these many top connectivities. May help with population independence and improve the tidiness of clustering. The lower the value the more independent the individual populations, at the cost of more conserved batch effect. If `None` (default), sets the parameter value automatically to 10 times `neighbors_within_batch` times the number of batches. Set to 0 to skip. |`integer`                             |

## Authors

  * Dries De Maeyer [{{< fa brands github >}}](https://github.com/ddemaeyer) (author)
  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (maintainer)
