---
title: "Build bdrhap reference"
namespace: "Reference"
description: "Compile a reference into a STAR index compatible with the BD Rhapsody pipeline."
toc: false
---

::: {.column-margin}

### Info

ID: `build_bdrhap_reference`  
Namespace: `reference`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/reference/build_bdrhap_reference){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script target/nextflow/reference/build_bdrhap_reference/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
genome_fasta: # please fill in - example: "genome_sequence.fa.gz"
transcriptome_gtf: # please fill in - example: "transcriptome_annotation.gtf.gz"
# output: "$id.$key.output.gz"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script target/nextflow/reference/build_bdrhap_reference/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name                  |Description                         |Attributes                                                     |
|:---------------------|:-----------------------------------|:--------------------------------------------------------------|
|`--genome_fasta`      |Reference genome fasta.             |`file`, required, example: `"genome_sequence.fa.gz"`           |
|`--transcriptome_gtf` |Reference transcriptome annotation. |`file`, required, example: `"transcriptome_annotation.gtf.gz"` |
|`--output`            |Star index                          |`file`, required, example: `"star_index.tar.gz"`               |

## Authors

  * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)
