---
title: "Scale"
namespace: "Transform"
description: "Scale data to unit variance and zero mean"
toc: false
---

::: {.column-margin}

### Info

ID: `scale`  
Namespace: `transform`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/transform/scaling){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script target/nextflow/transform/scale/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "input.h5mu"
modality: "rna"
# max_value: 123.0
zero_center: true
# output: "$id.$key.output.h5mu"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script target/nextflow/transform/scale/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name            |Description                                                                               |Attributes                                 |
|:---------------|:-----------------------------------------------------------------------------------------|:------------------------------------------|
|`--input`       |Input h5mu file.                                                                          |`file`, required, example: `"input.h5mu"`  |
|`--modality`    |List of modalities to process.                                                            |`string`, default: `"rna"`                 |
|`--max_value`   |Clip (truncate) to this value after scaling. Does not clip by default.                    |`double`                                   |
|`--zero_center` |If False, omit zero-centering variables, which allows to handle sparse input efficiently. |`boolean`, default: `TRUE`                 |
|`--output`      |Output h5mu file.                                                                         |`file`, required, default: `"output.h5mu"` |

## Authors

  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (maintainer)
