---
title: "Split modalities"
namespace: "Dataflow"
description: "Split the modalities from a single .h5mu multimodal sample into seperate .h5mu files."
toc: false
---

::: {.column-margin}

### Info

ID: `split_modalities`  
Namespace: `dataflow`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/src/dataflow/split_modalities){.btn-action .btn-sm .btn-info .btn role="button"}

:::




## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script target/nextflow/dataflow/split_modalities/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
input: # please fill in - example: "sample_path"
# output: "$id.$key.output.output"
# output_types: "$id.$key.output_types.csv"
compression: "gzip"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script target/nextflow/dataflow/split_modalities/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name             |Description                                                           |Attributes                                     |
|:----------------|:---------------------------------------------------------------------|:----------------------------------------------|
|`--input`        |Path to a single .h5mu file.                                          |`file`, required, default: `"sample_path"`     |
|`--output`       |Output directory containing multiple h5mu files.                      |`file`, required, example: `"/path/to/output"` |
|`--output_types` |A csv containing the base filename and modality type per output file. |`file`, required, example: `"types.csv"`       |
|`--compression`  |The compression format to be used on the final h5mu object.           |`string`, default: `"gzip"`                    |

## Authors

  * Dries Schaumont [{{< fa brands github >}}](https://github.com/DriesSchaumont) [{{< fa brands orcid >}}](https://orcid.org/0000-0002-4389-0440) (maintainer)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (contributor)
