---
title: "Demux"
namespace: "Ingestion"
description: "A generic pipeline for running bcl2fastq, bcl-convert or Cell Ranger mkfastq."
toc: false
---

::: {.column-margin}

### Info

ID: `demux`  
Namespace: `ingestion`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/workflows/ingestion/demux){.btn-action .btn-sm .btn-info .btn role="button"}

:::

Convert `.bcl` files to `.fastq` files using bcl2fastq, bcl-convert or Cell Ranger mkfastq.


## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script workflows/ingestion/demux/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Arguments
id: # please fill in - example: "foo"
input: # please fill in - example: "bcl_dir"
sample_sheet: # please fill in - example: "bcl_dir"
demultiplexer: "bcl2fastq"
# ignore_missing: true

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script workflows/ingestion/demux/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Arguments

|Name               |Description                                                    |Attributes                             |
|:------------------|:--------------------------------------------------------------|:--------------------------------------|
|`--id`             |ID of the sample.                                              |`string`, required, example: `"foo"`   |
|`--input`          |Input run directory                                            |`file`, required, example: `"bcl_dir"` |
|`--sample_sheet`   |Pointer to the sample sheet                                    |`file`, required, example: `"bcl_dir"` |
|`--demultiplexer`  |The multiplexer to use, one of bclconvert or mkfastq           |`string`, default: `"bcl2fastq"`       |
|`--ignore_missing` |Should the demultiplexer ignore missing entities (filter, ...) |`boolean`                              |

## Authors

  * Toni Verbeiren [{{< fa brands github >}}](https://github.com/tverbeiren) (author, maintainer)
  * Marijke Van Moerbeke [{{< fa brands orcid >}}](https://orcid.org/0000-0002-3097-5621) (author)
  * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
  * Samuel D'Souza [{{< fa brands github >}}](https://github.com/srdsam) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author)

## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p3(filter)
    p8(cellranger_mkfastq)
    p27(mix)
    p11(filter)
    p16(bcl_convert)
    p19(filter)
    p24(bcl2fastq)
    p32(fastqc)
    p35(Output)
    p37(toSortedList)
    p43(multiqc)
    p46(Output)
    p50(Output)
    p0-->p3
    p0-->p11
    p0-->p19
    p3-->p8
    p8-->p27
    p11-->p16
    p16-->p27
    p19-->p24
    p24-->p27
    p27-->p32
    p32-->p35
    p27-->p37
    p37-->p43
    p43-->p46
    p27-->p50

```
