---
title: "Process"
namespace: "Tabula sapiens"
description: ""
toc: false
---

::: {.column-margin}

### Info

ID: `process`  
Namespace: `tabula_sapiens`

### Links
[Source](https://github.com/czbiohub/utilities/blob/main/tabula_sapiens/process){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run czbiohub/utilities \
  -r main_build -latest \
  -main-script tabula_sapiens/process/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml

```
</details>

```bash
nextflow run czbiohub/utilities \
  -r main_build -latest \
  -profile docker \
  -main-script tabula_sapiens/process/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group

### Inputs

|Name            |Description                                                                            |Attributes                                                                                                 |
|:---------------|:--------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------|
|`--id`          |ID of the sample.                                                                      |`string`, required, example: `"foo"`                                                                       |
|`--input`       |The fastq.gz files to align. Can also be a single directory containing fastq.gz files. |`file`, required, example: `"sample_S1_L001_R1_001.fastq.gz"`, example: `"sample_S1_L001_R2_001.fastq.gz"` |
|`--reference`   |The path to Cell Ranger reference tar.gz file.                                         |`file`, required, example: `"reference.tar.gz"`                                                            |
|`--output_raw`  |The output h5mu.                                                                       |`file`, default: `"$id.output_raw"`                                                                        |
|`--output_h5mu` |The output h5mu.                                                                       |`file`, default: `"$id.output_h5mu.h5mu"`                                                                  |

## Authors

  * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)

## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p7(cellranger_count)
    p14(cellranger_count_split)
    p22(from_10xh5_to_h5mu)
    p29(cellbender_remove_background)
    p37(filter_with_counts)
    p41(Output)
    p0-->p7
    p7-->p14
    p14-->p22
    p22-->p29
    p29-->p37
    p37-->p41

```
