---
title: "Cell Ranger post-processing"
namespace: "Ingestion"
description: "Post-processing Cell Ranger datasets."
toc: false
---

::: {.column-margin}

### Info

ID: `cellranger_postprocessing`  
Namespace: `ingestion`

### Links
[Source](https://github.com/openpipelines-bio/openpipeline/blob/main/workflows/ingestion/cellranger_postprocessing){.btn-action .btn-sm .btn-info .btn role="button"}

:::



## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -main-script workflows/ingestion/cellranger_postprocessing/main.nf \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
# Inputs
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"

# Outputs
# output: "$id.$key.output.output"

# Correction arguments
perform_correction: false

# Filtering arguments
# min_genes: 100
# min_counts: 1000

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
```
</details>

```bash
nextflow run openpipelines-bio/openpipeline \
  -r main_build -latest \
  -profile docker \
  -main-script workflows/ingestion/cellranger_postprocessing/main.nf \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument groups

### Inputs

|Name      |Description                                                                       |Attributes                                |
|:---------|:---------------------------------------------------------------------------------|:-----------------------------------------|
|`--id`    |ID of the sample.                                                                 |`string`, required, example: `"foo"`      |
|`--input` |Input h5mu file created by running Cell Ranger and converting its output to h5mu. |`file`, required, example: `"input.h5mu"` |


### Outputs

|Name       |Description              |Attributes |
|:----------|:------------------------|:----------|
|`--output` |The converted h5mu file. |`file`     |


### Correction arguments

|Name                   |Description                                                   |Attributes     |
|:----------------------|:-------------------------------------------------------------|:--------------|
|`--perform_correction` |Whether or not to run CellBender to perform count correction. |`boolean_true` |


### Filtering arguments

|Name           |Description                                                              |Attributes                 |
|:--------------|:------------------------------------------------------------------------|:--------------------------|
|`--min_genes`  |Minimum number of counts required for a cell to pass filtering.          |`integer`, example: `100`  |
|`--min_counts` |Minimum number of genes expressed required for a cell to pass filtering. |`integer`, example: `1000` |

## Authors

  * Angela Pisco [{{< fa brands github >}}](https://github.com/aopisco) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-0142-2355) (author)
  * Robrecht Cannoodt [{{< fa brands github >}}](https://github.com/rcannood) [{{< fa brands orcid >}}](https://orcid.org/0000-0003-3641-729X) (author, maintainer)

## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
flowchart LR
    p0(Input)
    p7(from_10xh5_to_h5mu)
    p15(subset_h5mu)
    p21(filter)
    p26(cellbender_remove_background)
    p31(mix)
    p30(filter)
    p32(filter)
    p38(filter_with_counts)
    p42(mix)
    p41(filter)
    p48(publish)
    p54(Output)
    p30-->p31
    p31-->p32
    p31-->p41
    p41-->p42
    p0-->p7
    p7-->p15
    p15-->p21
    p15-->p30
    p21-->p26
    p26-->p31
    p32-->p38
    p38-->p42
    p42-->p48
    p48-->p54

```
