on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render project

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v3

      # - name: Replace Docker with podman
      #   run: |
      #     echo 'shopt -s expand_aliases' >> ~/.bash_profile
      #     echo 'alias docker=podman' >> ~/.bash_profile

      # - name: Check podman
      #   shell: bash -l {0}  
      #   run: |
      #     docker -v

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: "4.1"
      #     use-public-rspm: true

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      # - name: Install Nextflow
      #   env:
      #       CAPSULE_LOG: none
      #       NXF_VER: "22.04.5"
      #   run: |
      #     mkdir /tmp/nextflow
      #     cd /tmp/nextflow
      #     wget -qO- get.nextflow.io | bash
      #     sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
      #     nextflow -version
      
      # - name: Install latest Viash
      #   run: |
      #     wget https://github.com/viash-io/viash/releases/latest/download/viash -O /usr/local/bin/viash
      #     chmod +x /usr/local/bin/viash
      #     viash -v

      # - name: Install dependencies via renv restore
      #   run: |
      #     Rscript -e 'renv::restore()'
          
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 

      - name: Render with Quarto
        shell: bash -l {0}  
        run: |
          source renv/python/virtualenvs/renv-python/bin/activate
          quarto render docs

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_site
          branch: gh-pages
          force: false
          clean-exclude: pr-preview/

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto