build_docker_image:
  base_image: ubuntu:16.04

build_image:
  commands:
    $extend:
      - "apt-get update"
      - "apt-get install --yes alien"
      - "apt-get install --yes unzip"
      - "wget --quiet -P /tmp/ https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip"
      - "unzip /tmp/bcl2fastq2-v2-20-0-linux-x86-64.zip -d /tmp/"
      - "alien -i /tmp/bcl2fastq2-v2.20.0.422-Linux-x86_64.rpm"
      - "curl -L https://s3.amazonaws.com/czbiohub-scripts/other_software/cellranger-3.0.1.tar.gz > /tmp/cellranger.tar.gz"
      - "tar xfz /tmp/cellranger.tar.gz -C /tmp"
      - "mv /tmp/cellranger-3.0.1/* /usr/bin/"
      - "wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh"
      - "bash /tmp/miniconda.sh -b -p $HOME/anaconda"
      - "PATH=$HOME/anaconda/bin:$PATH"
      - "conda config --set always_yes yes --set changeps1 no"
      - "conda update -q conda"
      - "conda config --add channels defaults"
      - "conda config --add channels conda-forge"
      - "conda config --add channels bioconda"
      - "conda install -n root _license"
      - "conda info -a"
      - "git clone https://github.com/czbiohub/utilities.git"
      - "cd utilities"
      - "python setup.py install"
