functionality:
  name: "download_file"
  namespace: "download"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "robrecht@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  arguments:
  - type: "string"
    name: "--input"
    alternatives: []
    description: "URL to a file to download."
    example:
    - "https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_protein_v3/pbmc_1k_protein_v3_raw_feature_bc_matrix.h5"
    default: []
    required: true
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "Path where to store output."
    example:
    - "pbmc_1k_protein_v3_raw_feature_bc_matrix.h5"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--verbose"
    alternatives:
    - "-v"
    description: "Increase verbosity"
    direction: "input"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Download a file.\n"
  usage: "download_file \\\n  --input https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_protein_v3/pbmc_1k_protein_v3_raw_feature_bc_matrix.h5\
    \ \\\n  --output output_rna.h5\n"
  test_resources:
  - type: "bash_script"
    path: "run_test.sh"
    is_executable: true
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "bash:5.1.16"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/download/download_file/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/download/download_file"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/download/download_file/download_file"
  viash_version: "0.7.1"
  git_commit: "87117a5a2cbcae3a1822c26b043045a286f5e687"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
